### ISSUE TITLE
发送微信模版消息的Bug

### ISSUE THREAD

**Issue by skefy** [linlinjava/litemall#105]
问题代码处： org.linlinjava.litemall.core.notify.WxTemplateSender.java 中的sendMsg()  函数。

问题描述：调用微信模版消息的参数，多了一个 ‘color’ 参数，少了一个 “ access_token” 参数。

API参考地址：https://developers.weixin.qq.com/miniprogram/dev/api/sendTemplateMessage.html

**Comment by linlinjava** [comment]
我用的是这个开源软件 https://github.com/Wechat-Group/WxJava，里面的API就是这样的，你可以debug进去看看这里color参数怎么使用的。
