### ISSUE TITLE
你好，请问这个项目完成了吗？ 进度到了哪里？

### ISSUE THREAD

**Issue by ithjz** [linlinjava/litemall#106]
你好，请问这个项目完成了吗？ 进度到了哪里？
 怎么看到最新的进度

**Comment by linlinjava** [comment]
没有完成，正在第二阶段开发。

怎么看进度不清楚，要不你看看 [CHANGELOG](https://github.com/linlinjava/litemall/blob/master/CHANGELOG.md)
