### ISSUE TITLE
会员管理-编辑用户信息，密码会被修改的BUG

### ISSUE THREAD

**Issue by xiebaofu** [linlinjava/litemall#108]
会员管理-编辑用户信息，密码不是明文密码，而是经过加密的，然后保存的时候会再次加密，导致密码会被修改，原先的密码无法登陆

**Comment by linlinjava** [comment]
是的，需要修复这个问题。

**Comment by AloneWeb** [comment]
最好是后台不返回password字段（这个我不懂，可以叫大佬pr一下）
前端解决方案：
将password字段置空
`litemall-admin/src/views/user/user.vue`
![image](https://user-images.githubusercontent.com/22211269/50560600-75153100-0d3d-11e9-955a-27160568ead5.png)

**Comment by linlinjava** [comment]
嗯，谢谢，你这里两种解决方案都可以。
我也在思考是否后端不返回password。

**Comment by hack7621** [comment]
后端不应该返回密码，应该输入原密码和、新密码，后台先匹配数据库中原密码，一样在更新新密码。密码都加密匹配的，返回前端没用。

**Comment by linlinjava** [comment]
考虑到正常业务下面管理员不应该添加用户、编辑用户和删除用户，因此这些功能目前删除了。
因此用户密码修改功能不再支持，见 08bf8e0c18378b175082a980db14695bc5d136ee
