### ISSUE TITLE
添加统计销售金额功能

### ISSUE THREAD

**Issue by iamguofeng** [linlinjava/litemall#11]
希望大佬可以在后台管理界面，显示统计的销售金额。

**Comment by linlinjava** [comment]
统计功能是在业务开发规划中，技术上不难，只是业务上细节不明白。
是总的销售金额，还是不同月或者今日销售金额。
如果你能给出详细的效果或说明文档，这样开发的优先级会更高一些：）

**Comment by linlinjava** [comment]
实现了三个简单的统计页面。
你可以参考开发自己的统计页面。
