### ISSUE TITLE
命令行 npm run dev 报错

### ISSUE THREAD

**Issue by ziang-info** [linlinjava/litemall#111]
**命令行编译报错**
$ cnpm run dev

> litemall-admin@0.1.0 dev /Users/User/Documents/tech/litemall/litemall-admin
> cross-env BABEL_ENV=development webpack-dev-server --inline --progress --config build/webpack.dev.conf.js

 98% after emitting                                                                     

 ERROR  Failed to compile with 1 errors                                                          2:20:28 PM

This dependency was not found:

* @/views/profile/my in ./src/router/index.js

To install it, you can run: npm install --save @/views/profile/my

**页面显示错误：**
Failed to compile.

./src/router/index.js
Module not found: Error: Can't resolve '@/views/profile/my' in '/Users/User/Documents/tech/litemall/litemall-admin/src/router'

**Comment by ziang-info** [comment]
@linlinjava 能帮看一下 什么情况！？

**Comment by blowyang** [comment]
我也遇到这种情况，谁能解决下

**Comment by linlinjava** [comment]
你好，不是大问题，就是我添加了一个路由，但是忘了上传相应的my.vue页面。
我会提交的。

**Comment by linlinjava** [comment]
我删除了这里没有实现的路由信息，应该可以了。
