### ISSUE TITLE
数据库导入失败

### ISSUE THREAD

**Issue by shiliangL** [linlinjava/litemall#116]
![image](https://user-images.githubusercontent.com/24687496/51434573-f9086c00-1c9e-11e9-97ed-912ee0642a6e.png)

**Comment by linlinjava** [comment]
这个可能是不同的MySQL对sql语句支持不同吧。
你可以打开litemall_scheme.sql自己看一下，其实就是创建数据库、创建用户、分配权限。
所以这里你可以在数据库软件上手动完成这些操作。

**Comment by shiliangL** [comment]
好的 谢谢
