### ISSUE TITLE
邮箱通知收不到

### ISSUE THREAD

**Issue by liliuchen** [linlinjava/litemall#118]
smtp配置了，但是一直不成功，也没报错，能否把邮箱配置这块说详细一点

**Comment by linlinjava** [comment]
1. 文档里面[配置](https://linlinjava.gitbook.io/litemall/project#1-4-55-you-jian-tong-zhi-pei-zhi)
2. 你在application-core.yml配置好，邮件服务器也要配置好；
3. 你可以使用litemall-core模块的MailTest来单独启动系统发送邮件，然后自己登录邮箱看看有没有收到
