### ISSUE TITLE
小程序端emoji授权登录失败

### ISSUE THREAD

**Issue by blackdog1987** [linlinjava/litemall#119]
log：

	org.springframework.jdbc.UncategorizedSQLException: 
	### Error updating database.  Cause: java.sql.SQLException: Incorrect string value: '\xF0\x9F\x8D\xA7' for column 'nickname' at row 1
	### The error may involve org.linlinjava.litemall.db.dao.LitemallUserMapper.insertSelective-Inline
	### The error occurred while setting parameters
	### SQL: insert into litemall_user      ..........

失败原因是昵称nickname包含emoji表情。

解决方案：
1、自建mysql：修改`my.conf`（修改完成以后，需要重启mysql）

	[client]  
	default-character-set = utf8mb4  
	  
	[mysql]  
	default-character-set = utf8mb4  
	  
	[mysqld]  
	character-set-client-handshake = FALSE  
	character-set-server = utf8mb4  
	collation-server = utf8mb4_unicode_ci  
	init_connect='SET NAMES utf8mb4'

2、阿里云RDS：
https://help.aliyun.com/knowledge_detail/41702.html?spm=5176.10695662.1996646101.searchclickresult.2bc83086J1js5Q

3、执行sql：

        use mysql;
	ALTER DATABASE litemall CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

**Comment by linlinjava** [comment]
多谢，已经merge
