### ISSUE TITLE
优惠券无法兑换

### ISSUE THREAD

**Issue by mryu-org** [linlinjava/litemall#123]
环境：
1.最新版本代码
2.litemall-wx端无法兑换服务端生成的优惠码
兑换码无法点击

**Comment by mryu-org** [comment]
<img width="276" alt="00001" src="https://user-images.githubusercontent.com/9658267/52347595-45a0c500-2a5d-11e9-9191-ad15881eec82.png">

**Comment by linlinjava** [comment]
你这个优惠券效果不是最新的吧

你先更新一下到最新代码
