### ISSUE TITLE
小程序端无法获取到的快递单号

### ISSUE THREAD

**Issue by mryu-org** [linlinjava/litemall#124]
如图所示，shippername 和 shippercode获取到的值都为快递公司名称。
![01234](https://user-images.githubusercontent.com/9658267/52430019-1f078a80-2b40-11e9-8bc9-4206ea515d85.jpg)

**Comment by linlinjava** [comment]
你好，实际上这里只是简单调用第三方API，http://www.kdniao.com/api-track。
不过，你这里指出的问题很对，这里可能应该用logisticCode

**Comment by linlinjava** [comment]
fix 2232030f5db3edbb91d52b0ecc6e4c664ed9cf86
