### ISSUE TITLE
用户token用map管理，怎么保障线程安全和获取同步？

### ISSUE THREAD

**Issue by j2ee-haydon** [linlinjava/litemall#129]
private static Map<String, UserToken> tokenMap = new HashMap<>();
    private static Map<Integer, UserToken> idMap = new HashMap<>();

    public static Integer getUserId(String token) {
        UserToken userToken = tokenMap.get(token);
        if (userToken == null) {
            return null;
        }

        if (userToken.getExpireTime().isBefore(LocalDateTime.now())) {
            tokenMap.remove(token);
            idMap.remove(userToken.getUserId());
            return null;
        }

        return userToken.getUserId();
    }

看了下源码，Map的操作并非线程安全。是否其他地方有线程安全控制来保证？

**Comment by zhouqing86** [comment]
这里多线程访问有问题，应该至少用ConcurrentHashMap吧

**Comment by donghuan6** [comment]
我们是用redis

在 2019-03-02 07:13:57，"zhouqing86" <notifications@github.com> 写道：


这里多线程访问有问题，应该至少用ConcurrentHashMap吧

**Comment by linlinjava** [comment]
对，这里还需要进一步优化

**Comment by linlinjava** [comment]
这里采用 JWT，此外有些地方也采用ConcurrentHashMap来替代HashMap

**Comment by linlinjava** [comment]
这里采用 JWT，此外有些地方也采用ConcurrentHashMap来替代HashMap
