### ISSUE TITLE
按照介绍步骤完成，后台无法登陆

### ISSUE THREAD

**Issue by SCParrot** [linlinjava/litemall#136]
![后台状态图](https://user-images.githubusercontent.com/44453379/54072977-99046e00-42bc-11e9-86bd-30bb8c0873da.png)

导入数据库的时候，我修改了user
![数据库修改](https://user-images.githubusercontent.com/44453379/54072982-a1f53f80-42bc-11e9-9188-d72710f20678.png)
是不是java后台使用数据库填写的用户名密码与预设不同导致的，如果是的话，在哪里修改？

**Comment by linlinjava** [comment]
首先，先不要修改用户名和密码，数据库导入成功，看看后台能不能登录成功；
其次，如果登陆成功，再开始查看文档和代码，重新设置新的数据库用户名和密码；
最后，哪里修改，请文档多看看，或者代码多看看。
