### ISSUE TITLE
关于请求跨域的问题。

### ISSUE THREAD

**Issue by stonehiy** [linlinjava/litemall#14]
admin-api 启动后需要很久才能在vue-web页面接口很久才会响应POST请求，开始只是发送OPTIONS，不发送POST,十分钟后正常。node版本：8.0+

**Comment by linlinjava** [comment]
你好，其实我对node前端不是很懂，只是基于前端把业务搭起来。
你说的慢我是发现了，但是应该只是编译静态文件一次性请求导致的。
但是说要十分钟才能正常，这个我这里好像没有出现这个问题。
我在本地开发基本上管理后台的前端都能较快连上后台服务。

**Comment by stonehiy** [comment]
是我这边数据库版本问题，数据表没有导入完整，我现在用5.7好了，谢谢了

**Comment by linlinjava** [comment]
好的，那我也把这个数据库版本记在文档里面。
