### ISSUE TITLE
maven构建提示错误

### ISSUE THREAD

**Issue by yangqintaotomrose** [linlinjava/litemall#140]
[WARNING] The POM for com.github.pagehelper:pagehelper-spring-boot-starter:jar:1.2.5 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
找不到 import com.github.pagehelper.PageHelper; 这个class
导入这个依赖也没有            
<dependency>
                <groupId>com.github.pagehelper</groupId>
                <artifactId>pagehelper-spring-boot-starter</artifactId>
                <version>1.2.5</version>
            </dependency>

**Comment by linlinjava** [comment]
不太清楚你的意思，我这里一起正常。
项目下载以后，你应该使用```mvn install```命令按照依赖库。
