### ISSUE TITLE
项目可以 本地自服务启动

### ISSUE THREAD

**Issue by DongchenYear** [linlinjava/litemall#141]
创建service ：在 /etc/systemd/system 创建litemall.service
`
[Unit]
Description = Java Service of litemall
After network.target = litemall.service

[Service]
Type = forking
ExecStart = /home/XXX/deploy/bin/litemall.sh start
ExecStop = /home/XXX/deploy/bin/litemall.sh stop
ExecReload = /home/XXX/deploy/bin/litemall.sh reload

[Install]
WantedBy=multi-user.target

`

制作sh脚本
`#!/bin/sh
SERVICE_NAME=litemall
PATH_TO_JAR=/home/XXX/deploy/litemall/litemall.jar
PID_PATH_NAME=/home/XXX/deploy/tmp/litemall-pid
case $1 in
    start)
        echo "Starting $SERVICE_NAME ..."
        if [ ! -f $PID_PATH_NAME ]; then
            nohup java -jar $PATH_TO_JAR /home/XXX/deploy/tmp 2>> /dev/null >> /dev/null &
                        echo $! > $PID_PATH_NAME
            echo "$SERVICE_NAME started ..."
        else
            echo "$SERVICE_NAME is already running ..."
        fi
    ;;
    stop)
        if [ -f $PID_PATH_NAME ]; then
            PID=$(cat $PID_PATH_NAME);
            echo "$SERVICE_NAME stoping ..."
            kill $PID;
            echo "$SERVICE_NAME stopped ..."
            rm $PID_PATH_NAME
        else
            echo "$SERVICE_NAME is not running ..."
        fi
    ;;
    restart)
        if [ -f $PID_PATH_NAME ]; then
            PID=$(cat $PID_PATH_NAME);
            echo "$SERVICE_NAME stopping ...";
            kill $PID;
            echo "$SERVICE_NAME stopped ...";
            rm $PID_PATH_NAME
            echo "$SERVICE_NAME starting ..."
            nohup java -jar $PATH_TO_JAR /tmp 2>> /dev/null >> /dev/null &
                        echo $! > $PID_PATH_NAME
            echo "$SERVICE_NAME started ..."
        else
            echo "$SERVICE_NAME is not running ..."
        fi
    ;;
esac`

测试sh，
`bash litemall.sh start`
直接访问 IP:8080/wx/index/index
成功后

`sudo systemctl enable litemall.service`
开机启动
`sudo systemctl start litemall.service`
启动服务

完成～～

**Comment by linlinjava** [comment]
你好，非常感谢。
但是，这里想要讨论一下我现在的做法。
在deploy/bin/deploy.sh中
```
sudo service litemall stop
sudo ln -f -s /home/ubuntu/deploy/litemall/litemall.jar /etc/init.d/litemall
sudo service litemall start
```
也就是，这三个命令就部署服务成功了，所以不知道你这里这么复杂的原因。

**Comment by DongchenYear** [comment]
@linlinjava  那项目的日志放到哪里？我直接自定义日志路径

**Comment by DongchenYear** [comment]
那按你们这样做，项目的日志存在哪里？

**Comment by linlinjava** [comment]
你可以看一下spring boot官方文档，这是可以配置的。
当然这里采用默认方式，而默认好像是/var/log/litemall.log
