### ISSUE TITLE
orderDetail中代码不对吧

### ISSUE THREAD

**Issue by keweiLv** [linlinjava/litemall#143]
detail.js的去付款逻辑有点小问题吧，点击付款页面并不会跳转，微信工具控制台也有invoke提示，应该是最后少了一写其他逻辑判断。当然，也能是我本地代码有问题，仅做参考。

**Comment by linlinjava** [comment]
首先，这里代码是有一点小问题，就是没有处理请求后端失败的代码。
你可以看一下代码，只是处理了errno=0的情况，也就是请求成功的情况。

其次，这其实是小问题；相反，最重要的可能是你后端没有设置支付相关的配置信息，
因此后端微信支付相关代码会抛出异常，最终返回给前端报错信息。

最终，你可以自己仔细DEBUG一下，如果的确是支付没有配置，那么这里没有什么大的逻辑错误。
当然，关于未正确处理的代码目前暂时不会完善，你感兴趣的可以帮忙完善一下，谢谢。
