### ISSUE TITLE
litemall-wx checkout优惠券使用bug

### ISSUE THREAD

**Issue by funtask** [linlinjava/litemall#147]
再现过程
1.购物车选择商品a，checkout页面选择优惠券a
2.返回选择商品b，b商品不满足优惠券使用条件
页面出现bug

**Comment by linlinjava** [comment]
谢谢提醒，但是没有能够重现。
能不能再详细一点，或者进群交流一下。

**Comment by linlinjava** [comment]
你好，麻烦再详细一下重现过程，谢谢

**Comment by funtask** [comment]
前端couponId保存在本地缓存中，假如第二次选择商品不符合优惠券使用规则，服务端会返回 {"errno":402,"errmsg":"参数值不对"}，页面会显示错乱

问题代码WxCartController.java中checkout方法
```
            // 用户选择的优惠券有问题
            if(coupon == null){
                //return ResponseUtil.badArgumentValue();
                couponId=-1;
            }else{
                couponPrice = coupon.getDiscount();
            }
```

**Comment by linlinjava** [comment]
多谢，解决了，fix b252cf2b5bf5b0a5f43aa4d71f064dc5bb107335
