### ISSUE TITLE
vue tinymce 编辑器内容不会清除

### ISSUE THREAD

**Issue by YogaXiong1** [linlinjava/litemall#15]
例如，商品管理->添加商品，写完一个详细介绍后，再次点击添加，编辑器内容和之前的一样。

**Comment by linlinjava** [comment]
嗯，是的。

管理后台目前非常粗糙，但是目前仍在进行小商场前后台系统开发，之后会开始管理后台的开发，到时候会解决。

**Comment by bighector** [comment]
我的也有这个问题

**Comment by linlinjava** [comment]
修复 d96535756c465e27f9dc96997d5e72a06dc8bff7
