### ISSUE TITLE
商品在购物车中或订单中，后台无法编辑商品

### ISSUE THREAD

**Issue by Xu-TikT** [linlinjava/litemall#152]
一旦有用户把商品加入购物车或者订单中，后台便无法编辑商品

**Comment by linlinjava** [comment]
这里限制没有必要，目前已删除。
fix a0c58e083dd5b4199cc0993dc0ebd3a0511d055c

**Comment by Xu-TikT** [comment]
虽然限制去除了，但是在实际使用中，用户只要把商品提前加入了购物车仍然可以使用商品修改前的价格进行支付，这样的支付逻辑有漏洞

**Comment by linlinjava** [comment]
编辑商品，以及购物车商品更新 #293
