### ISSUE TITLE
验证码缓存map，过期验证码应该从map里移除。

### ISSUE THREAD

**Issue by CDNAME** [linlinjava/litemall#153]

**Comment by heyishi** [comment]
这样不安全 尤其在高并发下  建议 验证码放在redis 等成熟的中间件中


| |
He
|
|
heyishi@126.com
|
签名由网易邮箱大师定制


在2019年04月8日 21:38，CDNAME<notifications@github.com> 写道：

**Comment by linlinjava** [comment]
谢谢，你说的很对，不过redis的使用我准备放在第三阶段。

**Comment by CDNAME** [comment]
我简单改造了一下，使用concurrentHashmap代替普通的map。在新增验证码时，循环map，移除过期2分钟的entry。这样能保证map不会太大，不管是新增，遍历，查找都能比较高效。

**Comment by linlinjava** [comment]
可以，欢迎pr

**Comment by linlinjava** [comment]
另外，#129 是不是也可以这样处理

**Comment by selfuppen** [comment]
具有过期时间map的话，可以参考一下 https://github.com/jhalterman/expiringmap/
