### ISSUE TITLE
Druid设置 长时间不访问会导致mysql连接断开

### ISSUE THREAD

**Issue by dean403** [linlinjava/litemall#155]
Druid设置 长时间不访问会导致mysql连接断开, 建议更改下配置，也有可能是druid 版本的问题

**Comment by linlinjava** [comment]
那应该如何设置具体参数，希望分享一下你的配置。
druid版本可以升级，但是不知道是否能够解决你的问题。

**Comment by dean403** [comment]
还没解决... 目前排查到的问题估计是: mysql响应慢或者性能低下的时候，druid 创建连接超时，过期连接一直被移除 直到没有连接， mysql show full processlist 没有数据. 但是mysql服务是一直OK的 可以进行连接。
有个疑问就是mysql 恢复状态的时候， druid 不能重试建立连接 保持连接数？
希望协助解决下这个问题

**Comment by linlinjava** [comment]
不知道怎么协助，目前我云主机上面没有遇到问题，系统运行政策。

**Comment by dean403** [comment]
有过隔天不进行任何操作的case吗， Mysql 连接的一些设置是什么。 最大的问题是出在 druid 连接数不能保持，会被消耗干净...

**Comment by dean403** [comment]
如果应用配置没问题， 我重新弄一下我这边的Mysql服务...

**Comment by linlinjava** [comment]
http://118.24.0.153:8080/#/login
这个是管理后台演示地址，一般过几天登录没问题。

**Comment by dean403** [comment]
请问下作者，此项目中有一段时间大量读取磁盘或DB的操作或逻辑代码吗

**Comment by linlinjava** [comment]
有的，你看一下litemall-admin的job子包，会定时查询优惠券是否过期、订单是否过期的数据库查询、修改操作。当然，这里可能以后使用redis更好。

**Comment by dean403** [comment]
感谢，不是这边的问题，DB里没数据.
