### ISSUE TITLE
用户参加的团购活动到期没有满足人数条件，仍会按团购成功处理

### ISSUE THREAD

**Issue by Xu-TikT** [linlinjava/litemall#159]
用户参加的团购活动到期没有满足人数条件，订单仍是按团购成功处理，应该对团购失败的订单进行提示，并走人工退款流程

**Comment by linlinjava** [comment]
是的，团购业务是别人贡献的，可能还不完善，后面还会调整的，谢谢。

**Comment by zhangalex** [comment]
有些业务场景还真是允许这种事情发生。

**Comment by beaver383** [comment]
现在应该没有这个问题了，不过关于拼团期限仍有待商榷，
目前是以后台添加的团购规则中设置的结束时间作为所有相关团购活动的期限，
后续可能修改为创建团购活动后的一段时间（如24小时）内为团购活动期限，更符合日常的习惯

**Comment by linlinjava** [comment]
已经完成。
