### ISSUE TITLE
测试问题

### ISSUE THREAD

**Issue by cs0001** [linlinjava/litemall#16]
1、IOS在点击加入购物车按钮后，选择购买数量页面，没有加入购物车按钮

2、	登录后，点击头像账号没反应，无法退出
3、	点击去付款按钮没反应
4、	保存地址之后，回到地址列表页面，不会显示最新的地址，需退出后，重新进入才会显示，即没有刷新页面。
5、	商品详细页面，点击收藏按钮，报系统内部错误
6、	过期优惠卷还是显示在优惠卷列表中。

**Comment by cs0001** [comment]
请问这些问题近期能修复吗

**Comment by linlinjava** [comment]
你好，非常感谢你这里的反馈问题。我最近的规划是把微信支付整合到订单，然后修复一些小问题。你这里的问题我会之后看看怎么回事。
但是存在一个问题就是，我没有苹果手机，所以测试可能比较尴尬啊。
不知道你自己对前端熟悉吗，能不能解决一些呢，其实小程序也不难， 我自己java后端也是现学现卖。

**Comment by linlinjava** [comment]
1、IOS在点击加入购物车按钮后，选择购买数量页面，没有加入购物车按钮

修复

2、	登录后，点击头像账号没反应，无法退出
3、	点击去付款按钮没反应

这里无论是微信登录还是付款都是以下原因：

目前云后台服务设置是我申请的appid，而你不是我的体验用户，因此你微信登录你会失败的。
你可以自己在本地部署服务，在litemall-wx和litemall-wx-api的设置你的appid和appsecret。

此外，你要测试付款功能，你要在litemall-wx-api里面设置你申请的微信支付mch。

具体请参考本项目的文档。

4、	保存地址之后，回到地址列表页面，不会显示最新的地址，需退出后，重新进入才会显示，即没有刷新页面。

修复。

5、	商品详细页面，点击收藏按钮，报系统内部错误

修复。

6、	过期优惠卷还是显示在优惠卷列表中。

这个优惠券功能没有实现。你看到的只是静态页面，你也用不了。

因此，我将关闭这个issue。如果你觉得还有问题，你可以再打开issue。
