### ISSUE TITLE
打包部署是怎么操作的

### ISSUE THREAD

**Issue by xiaojia21190** [linlinjava/litemall#160]

**Comment by xiaojia21190** [comment]
![image](https://user-images.githubusercontent.com/16084693/56191558-22972080-605f-11e9-9657-6ec6d1188add.png)

**Comment by xiaojia21190** [comment]
现在打包直接报错了

**Comment by linlinjava** [comment]
仅供参考，可能部分有误
https://linlinjava.gitbook.io/litemall/project
https://linlinjava.gitbook.io/litemall/project#15-bu-shu-fang-an
https://linlinjava.gitbook.io/litemall/project#16-shang-xian-fang-an
