### ISSUE TITLE
nginx配置了https以后不后端不能访问

### ISSUE THREAD

**Issue by ynuchenqian** [linlinjava/litemall#161]
在本地和测试环境通过http的方式都没有问题可以访问，但是通过https证书加进来以后就不行了，前端页面请求后端就报错，提示：net::ERR_SSL_PROTOCOL_ERROR
![1](https://user-images.githubusercontent.com/15076533/56192503-190eb800-6061-11e9-8c4e-41d02b741df0.jpg)
另外我的nginx.conf的配置如下：
![2](https://user-images.githubusercontent.com/15076533/56192740-9fc39500-6061-11e9-8f34-b5c33db76b31.jpg)

**Comment by linlinjava** [comment]
关于https部署的问题，这里不是litemall项目本身的问题，建议你多实践或者百度看看
