### ISSUE TITLE
地址被删除后，checkout页面还是选择删除后的地址

### ISSUE THREAD

**Issue by funtask** [linlinjava/litemall#162]
checkout页面选择一个地址，此时addressId将保存本地缓存中，然后删除地址后，继续进入checkout页面会选择删除后的地址，原因服务端findbyaddres中找出了被删除地址的记录

**Comment by linlinjava** [comment]
嗯，是存在这个问题，谢谢。

**Comment by linlinjava** [comment]
目前采用优化前端逻辑，已经解决。fix edd0353694f41cef41e2665dae2b848494e2a41d

**Comment by funtask** [comment]
看了下修改还是有问题吧，
addressId = wx.getStorageSync('addressId')还是从本地缓存中取，地址被删除后，
请求http://localhost:8080/wx/cart/checkout?cartId=0&addressId=39&couponId=0&grouponRulesId=0
服务端还是可以找到这个被删除addressId地址

**Comment by linlinjava** [comment]
你说的对，欢迎督促！
fix again 8da0b5ec1c37e6c38719bc481de666fb08757da6
