### ISSUE TITLE
小程序点击微信登录  登录失败

### ISSUE THREAD

**Issue by MrJackC** [linlinjava/litemall#172]
本地局域网调试，后台完美运行，小程序导入的是wx版本，页面能正常加载，但是到了登录模块，点击登录，报错微信登录失败。还请指导一下。

**Comment by youaremywind** [comment]
请问是如何解决的{"errcode":40125,"errmsg":"invalid appsecret, view more at http://t.cn/RAEkdVq hint: [vT1u04943055]"}
	at cn.binarywang.wx.miniapp.api.impl.WxMaServiceImpl.getAccessToken(WxMaServiceImpl.java:134)
