### ISSUE TITLE
可以加入redis吗

### ISSUE THREAD

**Issue by BonnieCabrera** [linlinjava/litemall#175]
用户量大了，就很卡了

**Comment by linlinjava** [comment]
1. 如果你会技术，你可以先自己完善：）

2. 用户卡，我觉得应该测试是怎么引起的，也许redis不一定能解决卡的问题

3. 第三阶段有打算支持redis

**Comment by funtask** [comment]
可以先优化下索引

**Comment by linlinjava** [comment]
会的帮忙整一下啊，时间精力有限。

**Comment by enilu** [comment]
这个问题不是加入redis就能解决的
1，要先测试明确哪里卡，用户注册？登录？下单？搜索？查看商品详情？
2，卡的原因是什么？内存不够，带宽不够？数据库索引没有建立？
3，项目集成个redis很简单，关键要存什么信息，用户会话信息？购物车信息？。。。

**Comment by linlinjava** [comment]
enilu说的非常有道理，集成redis不难，难的在于明白redis的意义和正确使用方式，这里是需要思考的。

这也是为什么性能提升作为第三阶段的原因。
性能作为问题，答案不是简单的redis，也不是引入spring cloud就是万能，而是首先需要一个评价性能的方式，然后找到性能的瓶颈，最后查找解决瓶颈的技术方案。

**Comment by linlinjava** [comment]
关于redis使用的讨论与进展统一于 #53
