### ISSUE TITLE
请问管理员前端代码登录为什么会连接超时呀？

### ISSUE THREAD

**Issue by ZainZhao** [linlinjava/litemall#180]
后端启动正常

**Comment by ZainZhao** [comment]
2019年5月16日，我刚下的代码，但是管理员的api端口是8083，而管理员前端的代码是请求8080

**Comment by ZainZhao** [comment]
麻烦您看一下是不是开发配置有错误

**Comment by linlinjava** [comment]
你应该启动all模块，这个模块是封装了wx-api和admin-api模块，采用8080端口。

当然你可以单独启动admin-api模块，此时你需要手动调整admin前端模块的配置，把当前现在8080改成8083.

**Comment by linlinjava** [comment]
另外，文档多看一看

**Comment by ZainZhao** [comment]
我启动的就是all模块

**Comment by ZainZhao** [comment]
我没有修改过任何配置，启动的就是all模块，管理员的前端还是连接不上

**Comment by linlinjava** [comment]
你这样我怎么回答？

1. 告诉我commit版本
2. 告诉我你怎么运行的
3. chrome打开，看一下访问后端登录api的请求、响应情况，最后截屏。
4. 看一下提问的智慧，学习怎么更好的问问题，只有高质量的提问才有人愿意回答
