### ISSUE TITLE
微信litemall-wx首页团购商品和商品数目无法加载

### ISSUE THREAD

**Issue by Aron1995** [linlinjava/litemall#182]
litemall-wx和litemall-vue首页的团购商品信息加载不了，vue标签原因

**Comment by linlinjava** [comment]
目前litemall-wx这里没有发现团购有问题。
litemall-vue这里也没有问题，只是团购功能还没有调整好。

如果你觉得有问题，可以重新打开issue，然后补充详细信息，例如重现步骤，或者截屏。
