### ISSUE TITLE
在litemall-all下执行mvn spring-boot:run报 noRealm的错误

### ISSUE THREAD

**Issue by chenguangwei** [linlinjava/litemall#183]
错误日志：

```
No bean of type 'org.apache.shiro.realm.Realm' found.

Action:

Please create bean of type 'Realm' or add a shiro.ini in the root classpath (src/main/resources/shiro.ini) or in the META-INF folder (src/main/resources/META-INF/shiro.ini).

```
应该是 litemall_admin没有加载realm的问题 但是单独再litemall_admin下执行mvn spring-boot:run 是没有问题的

**Comment by chenguangwei** [comment]
修改了一下 pom文件 解决了

**Comment by chenguangwei** [comment]
修改了一下 pom文件 解决了

**Comment by Faynman-Dragon** [comment]
怎么解决的，可以说一下吗？

**Comment by chenguangwei** [comment]
把依赖的module中的 pom文件 里面的 build暂时去掉就可以了 例如 wx-api 和 admin-api里面的

**Comment by chenguangwei** [comment]
把依赖的module中的 pom文件 里面的 build暂时去掉就可以了 例如 wx-api 和 admin-api 模块pom文件里面的 <build>

**Comment by linlinjava** [comment]
你好，我也不知道为什么spring-boot:run 运行失败，你可以更新最新代码，然后采用java -jar来运行，我更新了readme文档了。

另外，我更新了spring boot到2.1.5了，好像也导致mvn打包出问题了，现在这个commit修复了，你们可以看一下 87b2c274c89f1350ab554a1c659ba4a91fc18e34
