### ISSUE TITLE
启动管理后台异常

### ISSUE THREAD

**Issue by laijinchuan** [linlinjava/litemall#185]
![图片](https://user-images.githubusercontent.com/45458746/58241586-da66ce80-7d7f-11e9-9522-66c9959d5e93.png)

**进入 litemall-all 之后 执行 mvn spring-boot:run 报错，报错信息如下** 

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v2.1.5.RELEASE)

2019-05-23 17:21:53.215 ERROR 26028 --- [  restartedMain] o.s.b.d.LoggingFailureAnalysisReporter   :

***************************
APPLICATION FAILED TO START
***************************

Description:

No bean of type 'org.apache.shiro.realm.Realm' found.

Action:

Please create bean of type 'Realm' or add a shiro.ini in the root classpath (src/main/resources/shiro.ini) or in the META-INF folder (src/main/resources/META-INF/shiro.ini).

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 24.354 s
[INFO] Finished at: 2019-05-23T17:21:53+08:00
[INFO] Final Memory: 33M/214M
[INFO] ------------------------------------------------------------------------

**Comment by linlinjava** [comment]
你好，我也不知道为什么spring-boot:run 运行失败，你可以更新最新代码，然后采用java -jar来运行，我更新了readme了。

**Comment by zhangran25** [comment]
我也遇到类似问题，请问这两种运行方式有何区别吗，为什么会有这个问题有结论了吗？还是说只能用java -jar运行？这样的话在编码调试阶段不能用IDEA来运行相对有点麻烦，另外不知道为什么总觉得心里别扭。。。。。。
