### ISSUE TITLE
vue可以动态菜单路由同时获取对应的shiro权限吗？？？

### ISSUE THREAD

**Issue by HalcyonDaysssss** [linlinjava/litemall#188]
`{
        path: 'os',
        component: () => import('@/views/sys/os'),
        name: 'os',
        meta: {
          perms: ['GET /admin/os/list', 'POST /admin/os/create', 'POST /admin/os/update', 'POST /admin/os/delete'],
          title: '对象存储',
          noCache: true
        }
      }`
目前perms这块是手动的，能做到动态路由同时获取对应菜单权限吗

**Comment by linlinjava** [comment]
需要看你到底需要什么效果。

这里的理念是这样的：
1. 后端返回用户权限
2. 前端手写路由，然后配置每个路由所需要的权限
3. 前端框架自动匹配路由所需权限和用户分配权限。

因此，你这里动态路由和菜单权限也是可行，
1. 后端可以根据权限返回路由，但是返回的路由里面不需要也不应该再设置perms，因为系统已经自动生成路由了。
2. 当然如果前端需要权限用于其他地方，也可以额外返回权限列表。
