### ISSUE TITLE
为什么 litemall-core 是一个可以启动的 Application，其他模块不是依赖 core 就能启动了吗？

### ISSUE THREAD

**Issue by yxxcoder** [linlinjava/litemall#189]
```java
@SpringBootApplication(scanBasePackages = {"org.linlinjava.litemall.db", "org.linlinjava.litemall.core"})
@MapperScan("org.linlinjava.litemall.db.dao")
public class Application {

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }

}
```

这样看起来 core 完全可以独立部署的，独立部署的话 core 与 admin-api 又是如何通信的呢？

**Comment by linlinjava** [comment]
core模块db模块，这是因为一些数据库配置需要db模块来访问数据库。

db模块和core模块都有Application类，但是你运行这两个Application会发现系统会自动退出，这是正常的，因为里面没有spring-web模块，所以就想一个普通的Public static void main方法，运行就结束了。

这里之所以也留着Application类，只是想可以单元运行db模块和core模块的测试类。例如db模块可以写测试类测试数据库访问相关代码，core模块可以写测试类测试相关通用代码。

如果你不需要你可以删除。

至于core和admin-api怎么通信，你可以看看代码，以及百度谷歌springboot多模块

**Comment by yxxcoder** [comment]
从代码上来看，core是不可以独立部署的，admin-api必须强依赖core。core依赖了spring-web模块，运行后不会像db一样马上结束，让人误以为core可以独立部署，通过dubbo之类框架与admin-api通信
