### ISSUE TITLE
购物车与直接下单逻辑

### ISSUE THREAD

**Issue by funtask** [linlinjava/litemall#190]
现在有个问题。直接下单后会清空购物车的商品（其他加入购物车但是未购买也会被删除），这个逻辑应该有问题吧

**Comment by funtask** [comment]
补充一个购物车的问题，商品下架后，已经添加进购物车的商品可以下单成功购买

**Comment by linlinjava** [comment]
感谢反馈，你测试的很仔细，细节方面的确可能存在你说的问题。
我会及时修复的

**Comment by cbsbaosen** [comment]
我这里也遇到了同样的问题，客户从购物车里按原规格买走了已经更换了规格的产品，呜呜，希望能帮忙尽快修复一下 @funtask @linlinjava

**Comment by linlinjava** [comment]
额，代码都在这里，为什么你们不能DEBUG解决一下，然后Pull Request啊

**Comment by linlinjava** [comment]
客户从购物车里按原规格买走了已经更换了规格的产品，这里是个问题。
我现在觉得采用技术不能很好地解决这个问题。因为如果用户修改规格，会导致之前的订单信息依赖使用被删除的规格信息，这样可能会出大问题。

其实现在正在考虑，不允许用户修改规格，只能下架商品上架新商品。当然可以简单支持用户修改商品部分信息，例如介绍和商品参数等。

不知道你们怎么考虑解决这里的问题。

**Comment by funtask** [comment]
主要我的代码改动的比较多....
是否可以在用户提交订单时检查关键的信息，价格，商品状态等？或者修改商品后购物车中的商品失效

**Comment by linlinjava** [comment]
你提的问题和上次的问题感觉可能需要数据库调整和业务调整一起来完成。。。

**Comment by ninghpTech** [comment]
这里可以同步修改规格数据以及购物车里对应商品的数据。

**Comment by linlinjava** [comment]
@ninghpTech 修改数据是可以同步。但是更严重的一种场景是，用户删除了商品规格或者添加新的规格，这导致商品的litemall_specification和litemall_product都会重建，而之前数据库里面的一些字段则指向旧的已经被删的litemall_specification和litemall_product表。由于商品是构建商场的基础数据信息，很多表都依赖这里，因此如果没有处理好，可能导致系统内部不一致。

**Comment by funtask** [comment]
同步购物车数据量小没问题，数据量上去了同步购物车开销有点大，感觉不是最佳解决方案。
我觉得可以增加个字段相当于商品编辑版本，商品修改后更新此字段，购物车可以比较此字段，判断商品是否已失效

**Comment by linlinjava** [comment]
@funtask 同上，我这里再次补充详细一下我理解的问题：
（1）商品信息多个表缓存问题，在一些表中保存了商品id和商品几个字段，因此如果商品编辑，则这些表需要同步更新，目前代码没有做，所以有问题；
针对这个问题，我觉得同步更新或者采用字段匹配是否旧信息，都是可行的，关键看具体业务需求。
（2）更为严重的是，商品存在规格表和货品表，如果用户删除当前规格，准备使用新的规格，那么会导致原规格数据和原货品无效，但是我觉得这会带来严重的问题，例如系统库存校验，对于同一个商品，存在旧货品和新货品，那么校验可能会存在很大问题。
针对这个问题，我目前觉得应该从业务方面限制用户操作，（1）允许用户编辑一部分商品信息，例如商品介绍，商品图片；（2）不允许用户添加、修改、删除规格和货品，或者允许用户修改规格和货品但不允许用户添加、删除；如果用户需要执行不允许的操作，则只能建议下降商品重新上架。
当然，这里我的理解，也可能不对，个人觉得比较麻烦，所以最好用户不要编辑商品。。。

**Comment by galenzhao** [comment]
我以前做的设计是，任何修改都会生成新的id，
同时ref上次的id，
这样新的查询只查新的，旧的订单内容保持不变

**Comment by flykingstar** [comment]
你好，我认为相比不让商户改规格，更好的处理方式是牺牲客户这边的一致性。客户打开购物车时，检查商品状态，如果被删除了，就给一个新的默认的规格（此处可以给客户提示信息也可以没有）。毕竟商户改规格如果要新建商品很多时候是很不情愿的，也不方便。这样也不会有数据一致性的问题，客户购物车永远是最新的商品信息。

**Comment by flykingstar** [comment]
客户的购物车里的变化，可以在第一次打开的时候，给一个提示商品信息已经变化之类的。

**Comment by flykingstar** [comment]
如果客户购买过程中，发生商户改商品信息，就提示，该商品信息已失效

**Comment by linlinjava** [comment]
@funtask 现在你提到的两个问题已经修复。
1 直接下单后不再清空购物车的商品
2 商品下架或删除后，系统自动清除失效购物车商品。当然这种实现方式可能效果不是很好。更好的效果应该是告知用户商品失效，提醒用户自己来删除。但是系统自动删除实现起来更简单。

对于商品已经更新场景下，购物车商品应该如此操作，这里我觉得不需要在这个issue中讨论。
请看 #293
