### ISSUE TITLE
litemall-rander收藏功能没有完善

### ISSUE THREAD

**Issue by jfmn01** [linlinjava/litemall#192]
litemall-rander商品详情页没有收藏功能

**Comment by linlinjava** [comment]
这里是特意这么做的。

litemall-wx的理念是后端功能都支持。
而renard-wx则是进一步简化，只支持最基本的购物流程即可。

**Comment by linlinjava** [comment]
如果你需要，可以参考litemall-wx的代码，然后加入到renard-wx
