### ISSUE TITLE
订单列表出现同一个订单编号，多条记录

### ISSUE THREAD

**Issue by jfmn01** [linlinjava/litemall#193]
下订单成功之后，取消这条订单，或者这条订单支付成功之后，订单列表会出现同一个订单编号，多条记录的情况，其中状态是不同的，但如果从别的页面再返回来看订单列表又正常了

**Comment by linlinjava** [comment]
你说的是哪个前端系统，我刚刚测试的litemall-wx没有出现这个问题。
如果你指的是litemall-vue系统，那有可能是有问题，因为订单那里还没有调整好。

**Comment by jfmn01** [comment]
是测试renard-wx发现的问题

**Comment by linlinjava** [comment]
看看是不是最新代码，我这里不能复现问题。
更希望你能自己debug一下，看看哪里有问题，帮忙解决一下。

**Comment by linlinjava** [comment]
测试了renard-wx，没有出现你说的问题，你下载最新代码看看吧。
