### ISSUE TITLE
苹果手机点击“微信直接登录”，登录失败

### ISSUE THREAD

**Issue by cbsbaosen** [linlinjava/litemall#201]
客户反映的问题，备注：不是所有苹果用户都有这个问题，同样是苹果X大多数都行，只有一两个不行。不知道其他人有没有遇到过这样的问题，给点思路。

**Comment by linlinjava** [comment]
买不起苹果的只能希望有人能解决，或者建议你到微信官方论坛找找。

**Comment by cbsbaosen** [comment]
原因找到了，不是苹果的问题，正在想解决问题的办法。是微信用户名里含有图片样式的字符，无论安卓还是苹果，存储数据写入Nickname字段就会报错。

**Comment by linlinjava** [comment]
应该是emoji引起的，你可以看看 #119

**Comment by cbsbaosen** [comment]
嗯，刚看到回复，已经解决了。和#119一样，谢谢呀
