### ISSUE TITLE
建议前后台代码分别放在两个文件夹下

### ISSUE THREAD

**Issue by ynp** [linlinjava/litemall#206]
建议前后台代码建议分别放在两个文件夹下，否则 导入eclipse前端代码也会导入，大量前端代码会导致eclipse假死。

**Comment by AloneWeb** [comment]
这个可以看FAQ里面的解决方案：https://linlinjava.gitbook.io/litemall/faq

**Comment by linlinjava** [comment]
首先，你的建议我自己已经考虑过，目前没有这么做，基于以下考虑：litemall-admin-api和litemall-admin放在一个目录下面，可以清晰地显示两者前后端关系，而放在不同文件夹可能显示不出来；如果把后端代码都放到一个文件夹下面，可能大家会想当然地认为需要启动所有模块，而实际上是可以分别部署litemall-admin-api模块和litemall-wx-api模块地；

其次，我在文档多个地方都提到了IDEA系统卡顿问题，特别是FAQ里面写的很清楚，因此可以暂时解决这个问题；

最后，以后也许会采用这里的建议放在不同的文件夹，来避免这个问题。
