### ISSUE TITLE
展示类精简版

### ISSUE THREAD

**Issue by boboChina** [linlinjava/litemall#21]
楼主能否把那个小程序弄个精简版，只有展示相关的页面，如果涉及到购买流程的个人版的小程序没法发布，拜谢

**Comment by linlinjava** [comment]
你好，既然是商场，那么支付环节少不了的，后面的订单操作都会依赖这里的支付效果。

关于精简，我觉得如果你是一个开发者，你应该有能力自己来完成精简的工作，这样你才能够分析出当前代码的潜在问题。不要说小程序不会什么的，这个我也是基于已有开源项目现学现卖。
