### ISSUE TITLE
订单相关功能不能进入及统计报表数据显示错误

### ISSUE THREAD

**Issue by staneychan** [linlinjava/litemall#211]
1 ) 无法进入 : 商场管理->订单管理
     没有跳转订单相关信息页面，一直在进度条加载中
2 ) 数据显示错误 : 统计报表->订单统计
     订单统计无论下了多少单一直都是显示一单

测试方法：编译litemall-wx小程序或renard-wx小程序，并填写相关的appid，并支付成功后，在后台查看，发现无法进入订单相关信息。

**Comment by linlinjava** [comment]
1. 第一个问题不能复现，建议你再试试

2. 第二个问题，你可以看litemalld-db模块下面resources的src/main/resources/org/linlinjava/litemall/db/dao下面的StatMapper.xml文件，
这里面订单统计是
```
 <select id="statOrder" resultType="map">
        select
        substr(add_time,1,10) as day,
        count(id) as orders,
        count(distinct user_id) as customers,
        sum(actual_price) as amount,
        round(sum(actual_price)/count(distinct user_id),2) as pcr
        from litemall_order
        where order_status in(103)
        group by substr(add_time,1,10)
    </select>
```
这里会统计订单状态103的订单，其实我这里可能写错了，我准备改成401和402，见 commit 5b0067015a9e91e7b256908e80207cd259eb6caf，也就是已确认订单和系统确认的订单。但是就算改成这样，你下的单也不会被统计，因此下订单的这些订单不属于用户确认或者系统确认。

这里如果你想统计自己需要的订单情况，你可以参考这里的代码实现新的统计效果。

**Comment by staneychan** [comment]
好的。难道这跟系统有关系？我让litemall.jar运行在虚拟机centOS7.6上.
那我再安装个ubuntu的试试看。
另外，centOS上有防火墙的，但我怎么想也跟这个没有什么关系的。对了，我也seteoforce 0了，这基本就与防火墙没什么关联了。
感觉莫名其妙的，不知点击：商场管理->订单管理
在哪个页面会进行什么检查和处理？我加些LOG打印上去看看。

**Comment by linlinjava** [comment]
你先确定本地开发环境下面，能不能进入订单页面。
可以使用内网穿透的方式暂时对外公共服务进行测试。

**Comment by staneychan** [comment]
@linlinjava 
经过我大量的对比验证发现还是不行。先说结果：
1. 在本地开发访问localhost的时候，可以进入订单管理。
2.当以dep打包成litemall.jar包时，通过java -jar litemall.jar运行起来后，
无论本地访问还是其他电脑访问管理后台（如:http://192.168.1.223:8080/#/login），都无法进入订单管理

我已经在本机win7,64和虚拟机centOS7.6和Ubuntu16.4LTS都运行过了，同样进入后台都不能访问订单管理。mysql用户也试过用root，同样不行。不知道linlin大是否有什么建议可提供？

**Comment by staneychan** [comment]
lin大，其他所有模块都可以进入，唯独订单管理不能进入，让我感觉非常奇怪。
我对vue不太熟悉。不知应该从何处调试可以分析出来？
感觉可能某个路径不存在或者访问超时的样子，所以我想通过打印LOG的方式找原因。
如果解决掉了，相信可以让后来者少走我这个弯路。

**Comment by darkness301** [comment]
@linlinjava，@staneychan, 大家好，我也发现类似问题。
1. 首先，在dev中，访问localhost的时候，可以进入订单管理，但是dep中，无论是服务器还是内网IP会出现订单管理无法进入的问题。
2. 在访问统计报表－>订单统计时会出现“系统内部错误”，进过排查，发现可能是 commit 5b00670提交时一个标点符号问题：
                        “where order_status in(103)
                         where order_status in(401， 402)”

where order_status in(401， 402)中的逗号好像是中文字符，将其改为 where order_status in(401, 402)后该问题解决，@staneychan, 你打印的log我也同样打出来，应该是这个符号问题引起的，和订单管理无法进入好像是不同的问题。

我会继续排查相关问题，希望和大家共同解决。

**Comment by staneychan** [comment]
@darkness301 
终于有人与我有相同问题的了。我在win,centOS,Ubuntu都百分百出现的问题，不知道为何在lin大那就不会出现。
经你这么一说，我大概知道了。也应该是同样的问题。
看StatMapper.xml:
    <select id="statOrder" resultType="map">
        select
        substr(add_time,1,10) as day,
        count(id) as orders,
        count(distinct user_id) as customers,
        sum(actual_price) as amount,
        round(sum(actual_price)/count(distinct user_id),2) as pcr
        from litemall_order
        where order_status in(401， 402)
        group by substr(add_time,1,10)
    </select>
这里也是同样的问题。

**Comment by darkness301** [comment]
@staneychan，我有点怀疑是端口的问题，正在排查。我用不同的端口得到不一样的结果，http://localhost:9527这个端口就可以访问订单管理，http://localhost:8080这个就不能访问订单管理。

**Comment by staneychan** [comment]
@darkness301 
我跟lin大沟通讨论后，lin大调试发现这个文件：chunk-beb4.b8ca8249.css
内容是空，加载上述的css报404

**Comment by linlinjava** [comment]
你好，我发现是前端错误，这里问题是这样的：
1. 在order.vue页面中存在空的style样式，这导致编译时生成chunk-beb4.b8ca8249.css文件里面是空；
2. 部署服务器以后，前端请求chunk-beb4.b8ca8249.css时，因为是空文件所以后端可能认为文件不存在而返回404错误码
3. 订单页面请求加载chunk-beb4.b8ca8249.css时返回404，因此订单页面的后续过程就失败，所以页面一直加载不出来。

修复方式见commit 156e79db284cbfbb77f64cbbf558bb9f0e717c60，也就是删除这个空的style语句就可以了。

感谢你们发现的问题。
