### ISSUE TITLE
按照步骤部署，提示登陆超时

### ISSUE THREAD

**Issue by chentengming** [linlinjava/litemall#212]
![1561174670(1)](https://user-images.githubusercontent.com/10330569/59959033-6d5f6980-94e2-11e9-91df-98359ab2bdf9.jpg)

**Comment by chentengming** [comment]
配置文件没有配好，已经OK了

**Comment by oftenliu** [comment]
@chentengming  你好，请问下你修改了哪里？我也遇到了这个问题
