### ISSUE TITLE
轻商城前端编译不通过

### ISSUE THREAD

**Issue by xy83918** [linlinjava/litemall#213]
`> litemall-vue@0.1.0 dev /root/code/litemall/litemall-vue
> vue-cli-service serve

/root/code/litemall/litemall-vue/node_modules/_open@6.3.0@open/index.js:11
const wslToWindowsPath = async path => {
                               ^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/root/code/litemall/litemall-vue/node_modules/_@vue_cli-shared-utils@3.8.0@@vue/cli-shared-utils/lib/openBrowser.js:9:14)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! litemall-vue@0.1.0 dev: `vue-cli-service serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the litemall-vue@0.1.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-06-23T05_10_15_821Z-debug.log`

**Comment by xy83918** [comment]
`5 info lifecycle litemall-vue@0.1.0~predev: litemall-vue@0.1.0
6 info lifecycle litemall-vue@0.1.0~dev: litemall-vue@0.1.0
7 verbose lifecycle litemall-vue@0.1.0~dev: unsafe-perm in lifecycle true
8 verbose lifecycle litemall-vue@0.1.0~dev: PATH: /usr/lib/node_modules/cnpm/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/root/code/litemall/litemall-vue/node_modules/.bin:/usr/java/jdk1.8.0_202/bin:/usr/local/nginx/sbin:/usr/local/mysql/bin:/usr/local/sbin:/sbin:/bin:/usr/sbin:/usr/bin:/root/maven/bin:/root/bin
9 verbose lifecycle litemall-vue@0.1.0~dev: CWD: /root/code/litemall/litemall-vue
10 silly lifecycle litemall-vue@0.1.0~dev: Args: [ '-c', 'vue-cli-service serve' ]
11 silly lifecycle litemall-vue@0.1.0~dev: Returned: code: 1  signal: null
12 info lifecycle litemall-vue@0.1.0~dev: Failed to exec dev script
13 verbose stack Error: litemall-vue@0.1.0 dev: `vue-cli-service serve`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/cnpm/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at EventEmitter.emit (events.js:191:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/cnpm/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at ChildProcess.emit (events.js:191:7)
13 verbose stack     at maybeClose (internal/child_process.js:920:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
14 verbose pkgid litemall-vue@0.1.0
15 verbose cwd /root/code/litemall/litemall-vue
16 verbose Linux 3.10.0-957.21.3.el7.x86_64
17 verbose argv "/usr/bin/node" "/usr/lib/node_modules/cnpm/node_modules/.bin/npm" "--userconfig=/root/.cnpmrc" "--disturl=https://npm.taobao.org/mirrors/node" "--registry=https://r.npm.taobao.org" "run" "dev"
18 verbose node v6.16.0
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 1
22 error litemall-vue@0.1.0 dev: `vue-cli-service serve`
22 error Exit status 1
23 error Failed at the litemall-vue@0.1.0 dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbosbbbbbb [ 1, true ]
se lifecycle litemall-vue@0.1.0~dev: CWD: /root/code/litemall/litemall-vue
10 silly lifecycle litemall-vue@0.1.0~dev: Args: [ '-c', 'vue-cli-service serve' ]
11 silly lifecycle litemall-vue@0.1.0~dev: Returned: code: 1  signal: null
12 info lifecycle litemall-vue@0.1.0~dev: Failed to exec dev script
13 verbose stack Error: litemall-vue@0.1.0 dev: `vue-cli-service serve`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/cnpm/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at EventEmitter.emit (events.js:191:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/cnpm/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at ChildProcess.emit (events.js:191:7)
13 verbose stack     at maybeClose (internal/child_process.js:920:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
14 verbose pkgid litemall-vue@0.1.0
15 verbose cwd /root/code/litemall/litemall-vue
16 verbose Linux 3.10.0-957.21.3.el7.x86_64`

**Comment by linlinjava** [comment]
首先，litemall-vue代码没有开发好，里面有些地方功能不对。
其次，我这里可以编译运行，使用的相关命令是
```
cnpm install
cnpm run dev
```
最后，建议你可以删除litemall-vue模块的node_modules文件夹或者清除缓存，重新下载依赖库再试试。

**Comment by xy83918** [comment]
`[root@instance-1 litemall-vue]# cnpm install

⠸ [6/18] Installing trim-right@^1.0.1
WARN node unsupported "node@v6.16.0" is incompatible with @vue/cli-service@^3.0.5, expected node@>=8
⠦ [8/18] Installing request@^2.87.0
WARN node unsupported "node@v6.16.0" is incompatible with @vue/cli-plugin-babel@3.8.0 › @vue/cli-shared-utils@3.8.0 › open@^6.3.0, expected node@>=8
⠏ [12/18] Installing @babel/core@^7.0.0
WARN node unsupported "node@v6.16.0" is incompatible with @vue/cli-service@3.8.4 › cli-highlight@^2.1.0, expected node@>=8.0.0
⠦ [12/18] Installing semver@^5.3.0
WARN node unsupported "node@v6.16.0" is incompatible with @vue/cli-service@3.8.4 › clipboardy@^2.0.0, expected node@>=8
⠏ [13/18] Installing camelcase@^3.0.0
WARN node unsupported "node@v6.16.0" is incompatible with @vue/cli-service@3.8.4 › default-gateway@^5.0.2, expected node@>=8
⠹ [14/18] Installing postcss-value-parser@^3.0.0platform unsupported @vue/cli-plugin-babel@3.8.0 › webpack@4.28.4 › watchpack@1.6.0 › chokidar@2.1.6 › fsevents@^1.2.7 Package require os(darwin) not compatible with your platform(linux)
[fsevents@^1.2.7] optional install error: Package require os(darwin) not compatible with your platform(linux)
⠸ [16/18] Installing mkdirp@0.5.x
WARN node unsupported "node@v6.16.0" is incompatible with @vue/cli-service@3.8.4 › read-pkg@^5.0.0, expected node@>=8
✔ Installed 18 packages
✔ Linked 972 latest versions
[1/3] scripts.postinstall @vue/cli-plugin-babel@3.8.0 › @vue/babel-preset-app@3.8.0 › @babel/runtime-corejs2@7.4.5 › core-js@^2.6.5 run "node scripts/postinstall || echo \"ignore\"", root: "/root/code/litemall/litemall-vue/node_modules/_core-js@2.6.9@core-js"
Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

[1/3] scripts.postinstall @vue/cli-plugin-babel@3.8.0 › @vue/babel-preset-app@3.8.0 › @babel/runtime-corejs2@7.4.5 › core-js@^2.6.5 finished in 2s
[2/3] scripts.install node-sass@^4.9.3 run "node scripts/install.js", root: "/root/code/litemall/litemall-vue/node_modules/_node-sass@4.12.0@node-sass"
Cached binary found at /root/.npminstall_tarball/node-sass/4.12.0/linux-x64-48_binding.node
[2/3] scripts.install node-sass@^4.9.3 finished in 9s
[2/3] scripts.postinstall node-sass@^4.9.3 run "node scripts/build.js", root: "/root/code/litemall/litemall-vue/node_modules/_node-sass@4.12.0@node-sass"
Binary found at /root/code/litemall/litemall-vue/node_modules/_node-sass@4.12.0@node-sass/vendor/linux-x64-48/binding.node
Testing binary
Binary is fine
[2/3] scripts.postinstall node-sass@^4.9.3 finished in 2s
[3/3] scripts.install @vue/cli-service@3.8.4 › yorkie@^2.0.0 run "node bin/install.js", root: "/root/code/litemall/litemall-vue/node_modules/_yorkie@2.0.0@yorkie"
setting up Git hooks
can't find .git directory, skipping Git hooks installation
[3/3] scripts.install @vue/cli-service@3.8.4 › yorkie@^2.0.0 finished in 419ms
✔ Run 3 scripts
peerDependencies link ajv@5.5.2 in /root/code/litemall/litemall-vue/node_modules/_ajv-keywords@2.1.1@ajv-keywords unmet with /root/code/litemall/litemall-vue/node_modules/ajv(6.10.0)
deprecate @vue/cli-plugin-eslint@3.8.0 › eslint@4.19.1 › file-entry-cache@2.0.0 › flat-cache@1.3.4 › circular-json@^0.3.1 CircularJSON is in maintenance only, flatted is its successor.
deprecate @vue/cli-plugin-babel@3.8.0 › webpack@4.28.4 › micromatch@3.1.10 › snapdragon@0.8.2 › base@0.11.2 › mixin-deep@^1.2.0 Critical bug fixed in v2.0.1, please upgrade to the latest version.
deprecate @vue/cli-plugin-babel@3.8.0 › webpack@4.28.4 › micromatch@3.1.10 › snapdragon@0.8.2 › base@0.11.2 › cache-base@1.0.1 › set-value@^2.0.0 Critical bug fixed in v3.0.1, please upgrade to the latest version.
deprecate @vue/cli-plugin-babel@3.8.0 › webpack@4.28.4 › micromatch@3.1.10 › snapdragon@0.8.2 › base@0.11.2 › cache-base@1.0.1 › union-value@1.0.0 › set-value@^0.4.3 Critical bug fixed in v3.0.1, please upgrade to the latest version.
Recently updated (since 2019-06-16): 13 packages (detail see file /root/code/litemall/litemall-vue/node_modules/.recently_updates.txt)
  Today:
    → @vue/cli-plugin-babel@3.8.0 › @vue/cli-shared-utils@3.8.0 › @hapi/joi@^15.0.1(15.1.0) (07:40:53)
    → @vue/cli-service@3.8.4 › browserslist@4.6.3 › electron-to-chromium@^1.3.164(1.3.170) (12:02:34)
✔ All packages installed (1131 packages installed from npm registry, used 2m(network 1m), speed 306.66kB/s, json 990(2.05MB), tarball 24.29MB)
[root@instance-1 litemall-vue]# cnpm run dev


> litemall-vue@0.1.0 dev /root/code/litemall/litemall-vue
> vue-cli-service serve

/root/code/litemall/litemall-vue/node_modules/_open@6.3.0@open/index.js:11
const wslToWindowsPath = async path => {
                               ^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/root/code/litemall/litemall-vue/node_modules/_@vue_cli-shared-utils@3.8.0@@vue/cli-shared-utils/lib/openBrowser.js:9:14)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! litemall-vue@0.1.0 dev: `vue-cli-service serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the litemall-vue@0.1.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-06-23T13_44_21_573Z-debug.log
[root@instance-1 litemall-vue]#
[root@instance-1 litemall-vue]#`

**Comment by xy83918** [comment]
所以是我node版本不对是吗？

**Comment by xy83918** [comment]
刚刚把node6 升级到node8 编译没有问题了
