### ISSUE TITLE
代码规范以及延迟任务引入

### ISSUE THREAD

**Issue by SoberChina** [linlinjava/litemall#215]
无用的引用以及日志打印，订单取消/优惠券过期采用定时任务，为什么不采用延迟调度呢？

**Comment by linlinjava** [comment]
延迟调度技术不太会，如果你比较熟练，欢迎重构这里的定时任务，谢谢。
我也觉得不是很合理，但是还没有解决。

**Comment by SoberChina** [comment]
[参考这个](https://github.com/SoberChina/delay)

**Comment by linlinjava** [comment]
我看了，但是引入你这里技术栈需要依赖rabbitmq+redis+quartz三种，目前我还是想保持项目的简单吧。

**Comment by SoberChina** [comment]
好吧
