### ISSUE TITLE
分类中/items/list页面，随便点击详细，会报错，没有itemClick方法。

### ISSUE THREAD

**Issue by Sancly** [linlinjava/litemall#222]
![image](https://user-images.githubusercontent.com/37282244/60566749-6e25b480-9d9a-11e9-9fe3-fdec63bf6d70.png)
![image](https://user-images.githubusercontent.com/37282244/60566759-7c73d080-9d9a-11e9-9c6f-9461873af628.png)

**Comment by linlinjava** [comment]
fix 9060274daf9886c6686088d3ecd1a7c7ee8a860d
