### ISSUE TITLE
文档说明错误

### ISSUE THREAD

**Issue by selfuppen** [linlinjava/litemall#225]
api 的2 基础系统里：
2.1.4.2 状态变化
101 -> 103 系统会自动取消订单
“ 所对应的后台服务方法是litemall-admin-api模块的AdminOrderController.checkOrderUnpaid”
对应的应该是litemall-admin-api模块的系统定时任务OrderJob.checkOrderUnpaid。

**Comment by selfuppen** [comment]
> 
> 
> api 的2 基础系统里：
> 2.1.4.2 状态变化
> 101 -> 103 系统会自动取消订单
> “ 所对应的后台服务方法是litemall-admin-api模块的AdminOrderController.checkOrderUnpaid”
> 对应的应该是litemall-admin-api模块的系统定时任务OrderJob.checkOrderUnpaid。

还有“所对应的后台服务方法是litemall-admin-api模块的AdminOrderController.checkOrderUnpaid”
也应该是litemall-admin-api模块的系统定时任务OrderJob.checkOrderUnpaid

**Comment by linlinjava** [comment]
谢谢，文档看的很仔细，欢迎反馈文档任何不合理的地方， fix 6aa5fdf9cf0f5c3c665c2b4de6b6f0da2d7e236b
