### ISSUE TITLE
多商城应该怎么做

### ISSUE THREAD

**Issue by xiaojia21190** [linlinjava/litemall#228]

**Comment by dannyZhou** [comment]
我也在考虑同样的问题， 我打算 fork 一份，然后基于某一个 版本开始更改

**Comment by dannyZhou** [comment]
@linlinjava 如果我打算基于 litemall 开发多商户商城管理系统的话，我应该遵循什么样的协议？我需要注意什么？如果后期我用于商用，我该注意什么？
