### ISSUE TITLE
代码的几点小建议

### ISSUE THREAD

**Issue by zhongyusimon** [linlinjava/litemall#231]
1. 代码在做数字比较的时候不要用equal，equal是比对两个对象的值是否一致。如果直接和int做比较，使用==就行，不然会比对失败。
2. 在返回数据的时候，能用批量查询的最好能用批量查询，会提升不少效率，比如在couponController里面，可以直接查出所有的coupon，在for循环里面查的话，会多次跟mysql交互数据，效率降低
```java
private List<CouponVo> change(List<CouponUser> couponList) {
        List<CouponVo> couponVoList = new ArrayList<>(couponList.size());
        for(CouponUser couponUser : couponList){
            Long couponId = couponUser.getCouponId();
            Coupon coupon = couponService.findById(couponId);
            CouponVo couponVo = new CouponVo();
            couponVo.setId(coupon.getId());
            couponVo.setName(coupon.getName());
            couponVo.setDesc(coupon.getCouponDesc());
            couponVo.setTag(coupon.getTag());
            couponVo.setMin(coupon.getMin().toPlainString());
            couponVo.setDiscount(coupon.getDiscount().toPlainString());
            couponVo.setStartTime(couponUser.getStartTime());
            couponVo.setEndTime(couponUser.getEndTime());

            couponVoList.add(couponVo);
        }

        return couponVoList;
    }
```

**Comment by linlinjava** [comment]
>

> 1. 代码在做数字比较的时候不要用equal，equal是比对两个对象的值是否一致。如果直接和int做比较，使用==就行，不然会比对失败。

实际上，项目一开始是采用==比较，但是出现了bug，即Integer对象比较失败，因此这里统一采用equal。对于Integer和int比较，equal和==都是可以的；对于Integer和Integer比较，则必须采用equal比较。所以我觉得这里最后所说的对比失败的结论可能是不正确的。这篇文章介绍的不错，https://www.cnblogs.com/jiagoushi/p/9943637.html

> 2. 在返回数据的时候，能用批量查询的最好能用批量查询，会提升不少效率，比如在couponController里面，可以直接查出所有的coupon，在for循环里面查的话，会多次跟mysql交互数据，效率降低
> 
你这里的建议是对的，后面应该要重构这里。

> ```java
> private List<CouponVo> change(List<CouponUser> couponList) {
>         List<CouponVo> couponVoList = new ArrayList<>(couponList.size());
>         for(CouponUser couponUser : couponList){
>             Long couponId = couponUser.getCouponId();
>             Coupon coupon = couponService.findById(couponId);
>             CouponVo couponVo = new CouponVo();
>             couponVo.setId(coupon.getId());
>             couponVo.setName(coupon.getName());
>             couponVo.setDesc(coupon.getCouponDesc());
>             couponVo.setTag(coupon.getTag());
>             couponVo.setMin(coupon.getMin().toPlainString());
>             couponVo.setDiscount(coupon.getDiscount().toPlainString());
>             couponVo.setStartTime(couponUser.getStartTime());
>             couponVo.setEndTime(couponUser.getEndTime());
> 
>             couponVoList.add(couponVo);
>         }
> 
>         return couponVoList;
>     }
> ```

**Comment by spinachomes** [comment]
使用基本类型包装类型比较的话还是equals，包装类与基本类型用== ，大于127就可能有问题了
