### ISSUE TITLE
请问，litemall-wx微信小程序端是怎么分页的

### ISSUE THREAD

**Issue by HuhaStephen** [linlinjava/litemall#237]
找了半天，都是把page=1，limit=10，后续就没了

**Comment by linlinjava** [comment]
你这里思路有问题，的确有些小程序页面没有分页，那是因为这里没有实现或者不需要实现而已。
如果你想学习小程序端怎么分页，你可以看看一些已经有分页效果的页面，仔细看看代码自然明白。

**Comment by HuhaStephen** [comment]
你好，我是看了本项目的小程序没发现分页地方，怀疑是我没找到。作者能告知是什么页面实现了分页吗，我去参考一下，还是分页功能还在计划中呢？

**Comment by HuhaStephen** [comment]
你好，我是看了本项目的小程序没发现分页地方，怀疑是我没找到。作者能告知是什么页面实现了分页吗，我去参考一下，还是分页功能还在计划中呢？
