### ISSUE TITLE
管理端删除、修改商品，小程序购物车内的商品状态没有改变

### ISSUE THREAD

**Issue by marsoop** [linlinjava/litemall#240]
在管理端修改、删除商品，小程序购物车内的商品仍然是之前的状态。这个可以做成类似淘宝的商品失效吗？有思路可以提供吗？

**Comment by linlinjava** [comment]
是的，这里有问题。

购物车里面缓存了少量商品信息，本来是想减少对商品的查询，直接返回购物车商品的信息。
比较简单的做法可能是，在购物车商品里面设置一个字段记录是否失效，当后端修改或者删除商品，后端会查询所有购物车商品，如果存在则记录失效字段，而下单时则需要后端检查是否购物车商品已经失效。

**Comment by linlinjava** [comment]
编辑商品，以及购物车商品更新 #293
