### ISSUE TITLE
Cannot assign to read only property 'exports' of object '#<Object>'

### ISSUE THREAD

**Issue by wenxiayili** [linlinjava/litemall#242]
管理后台前端，运行命令，npm run dev。页面不能显示，然后下面是堆栈截图：
![image](https://user-images.githubusercontent.com/24307095/62202905-bf868b00-b3bc-11e9-9343-982e2db5af4b.png)

![image](https://user-images.githubusercontent.com/24307095/62202933-c9a88980-b3bc-11e9-8534-6318faba8791.png)

运行环境：win10
npm：6.3.0
webpack: 4.38.0
麻烦作者能告诉下这是什么情况吗？

**Comment by beaver383** [comment]
npm 6.9.0
webpack 4.35.2

未遇到该问题

**Comment by linlinjava** [comment]
建议你删除node_modules目录，然后重新install。
目前没有遇到过你这里的问题。

**Comment by wenxiayili** [comment]
> 
> 
> 建议你删除node_modules目录，然后重新install。
> 目前没有遇到过你这里的问题。

原因已找到 抱歉没有关闭， 是因为webapck的版本问题。TKS
