### ISSUE TITLE
外部配置文件没有读取生效

### ISSUE THREAD

**Issue by HelloZouYou** [linlinjava/litemall#248]
按照deploy下的文档打包jar后，外部配置文件application.yml里面的配置没有生效，或者说没有被读取，比如数据库host使用仍是代码里面本身的localhost，而不是jar包同级目录下配置文件中的host

**Comment by beaver383** [comment]
拷贝
litemall-db\src\main\resources\application-db.yml
litemall-core\src\main\resources\application-core.yml
至 deploy\litemall 目录
application.yml中只留port和log

**Comment by HelloZouYou** [comment]
@beaver383 是的，可以的，谢谢了

**Comment by linlinjava** [comment]
谢谢你反馈，我这里修复了一下 bd6aae97c760e5c5693b6088b73f8a69a6f1ad55。

这里我详细解释一下：

首先，你看litemall-all模块中的application文件
```
spring:
  profiles:
    active: db, core, admin, wx
```
通过这种方式会自动加载其他模块的配置文件。
这是一种多配置文件的方式。

然而，我在deploy文件夹中又采用单一配置文件方式，就是所有配置属性都写在了application配置文件中，而不是分散的多个配置文件。

需要说明的是，这两种方式都是可行的，这里deploy采用单一方式，仅仅是因为考虑当前目录下只有一个litemall.jar可执行文件，因此配合一个外部配置文件可能更为合理些。

最后，解释一下，为什么你之前会出问题，以及我这次fix的方式。
之前我一直错误地认为spring boot的二进制jar包优先读取当前目录下的application文件，从而可以覆盖模块内部的application文件，但是因为你的问题，我又查了一下，发现spring boot二进制包的确会优先读取外部配置文件，但是同时也会读取内部配置文件，最后把所有配置组合在一起(当然相同的配置，外部优先）。之前外部配置文件中没有写spring.profiles.active，而all内部模块配置文件中有spring.profiles.active，因此导致了一个问题，就是外部配置文件虽然读取了，但是内部模块配置文件中有spring.profiles.active也引入生效，从而会尝试去读取那些db, core, admin, wx配置文件。

总之，建议你这里pull最新代码再尝试一下看看，此时应该会配置生效了。

**Comment by HelloZouYou** [comment]
@linlinjava 感谢您的回复，之前看到 project.md 中关于 [spring.profiles.active](https://github.com/linlinjava/litemall/blob/master/doc/project.md#145-%E9%A1%B9%E7%9B%AE%E9%85%8D%E7%BD%AE) 的描述想过可能缺少类似配置，但遗憾没有去尝试合并过来，稍候会尝试最新代码，再次感谢！
