### ISSUE TITLE
配置后台失败

### ISSUE THREAD

**Issue by wcngsb** [linlinjava/litemall#249]
请问：
java -Dfile.encoding=UTF-8 -jar litemall-all/target/litemall-all-0.1.0-exec.jar
提示
Table 'litemall.litemall_system' doesn't exist
怎么解决哈？

**Comment by beaver383** [comment]
拷贝
litemall-db\src\main\resources\application-db.yml
litemall-core\src\main\resources\application-core.yml
至 deploy\litemall 目录
application.yml中只留port和log

**Comment by linlinjava** [comment]
错误很明显，数据库表不存在，请仔细按照文档把数据库litemall数据库及测试数据弄好
