### ISSUE TITLE
generateOrderSn()这里生成唯一订单

### ISSUE THREAD

**Issue by Sunyb01** [linlinjava/litemall#258]
生成唯一订单可以考虑UUID加时间这样重复的几率应该会更低吧?

**Comment by linlinjava** [comment]
这是可行的，你也可以试试。
目前这里假定是小商城，因此可能一天订单也不会太多。
当然，如果因为什么活动造成瞬时大量订单，那么有可能需要改善

**Comment by alexzhu0592** [comment]
> 这是可行的，你也可以试试。
> 目前这里假定是小商城，因此可能一天订单也不会太多。
> 当然，如果因为什么活动造成瞬时大量订单，那么有可能需要改善

可以用snowFlake算法做一个uid生成器， @linlinjava 需要pr吗？

**Comment by linlinjava** [comment]
@alexzhu0592 谢谢啊，不过因为这里设想的是小微型商城，因此技术简单但是容易理解，我觉得虽然理论上存储重复概率，但是在设想场景下还是可以工作的。当然如果有什么活动，那还是自行扩展好了。
