### ISSUE TITLE
购物车fastAdd时，不会更新最新的商品属性。

### ISSUE THREAD

**Issue by selfuppen** [linlinjava/litemall#260]
购物车fastAdd和add时，若购物车存在同款商品，则商品的数据不会更新最新的商品信息。
如：当后台修改了商品价格后，继续添加购物车，购物车的商品不会及时更新，而是一开始填加的价格。

ps：
不知为什么，代码拉不下来。没法提pr。
代码定位：org.linlinjava.litemall.wx.web.WxCartController.add和org.linlinjava.litemall.wx.web.WxCartController.fastadd .

**Comment by linlinjava** [comment]
非常感谢反馈，现在的确存在一个很大的问题，就是商品的修改操作，目前实现肯定是有问题的，但是如何解决却不是很简单。你可以看看其他相关issue，就能发现修改商品，特别是已经下过订单的商品，到底是否应该支持修改，以及如何支持，都存在难点。

当然，如果有好的解决方案欢迎继续交流。

**Comment by beaver383** [comment]
建议涉及规格的商品修改都先下架处理，商品重新上架则复制数据并创建新的goods记录
这样就不会出现已经修改的商品规格仍然购买成功的情况，同时也不会影响已有业务

**Comment by linlinjava** [comment]
编辑商品，以及购物车商品更新 #293
