### ISSUE TITLE
下单时，如果购物车的商品已经删除，则会下单错误。

### ISSUE THREAD

**Issue by zhongyusimon** [linlinjava/litemall#261]
AdminGoodsService.java中，修改商品数据的时候，会把旧的数据删除，然后增加新的，如果在购物车中已经加入过这个商品，下单的时候就会报异常。

修改方式：
1. 在更新商品信息的时候，能修改的尽量做修改，不要删除后再修改。
2. 如果必须要做删除，则应该把购物车中的商品置为已下架，或者删除
3. 购物车在查询的时候，最好是也做判断商品是否还存在

**Comment by zhongyusimon** [comment]
刚看到你在函数上面的注释。 其实是可以解决的，你的几个数据里面已经加上id了，如果有id的就全部做更新，如果没有id的就是直接添加。 
再把原来的数据查询出来做对比，看看有没有不存在的一些数据，如果存在就是被删除的。这样就能作为更新操作了。

**Comment by zhongyusimon** [comment]
这里过两天我有空我可以帮忙改一下，不是很复杂。顺便也把购物车那里改一下，增加一个商品已下架的状态。可以在前端显示已下架，可以让用户自己删除，也可以在接口里面设置不展示。

**Comment by zhongyusimon** [comment]
我知道你修改起来的难点了。主要是在前端的处理上，增加和删除规格的时候，对商品的处理。修改方案可以如下：
删除规格的时候，必须查看是否有多个对应的商品，否则不允许删除。必须先把商品删除后，才能删除规格。
在添加规格的时候，需要给现有商品一个默认的规格值。 而且商品还能够动态的选择规格值，不能只是系统随机分配的。

最起码的修改是，不能每次修改商品信息的时候，都会把这三种属性全部删除，再重新添加，肯定是不合理的。

**Comment by linlinjava** [comment]
谢谢你这里的思考。
我觉得这里编辑商品难度在于，用户已经下单时商品已经绑定，此时你再修改商品，如何操作？

例如，假定用户A，已经买了商品B，其规格是[C1, C2]。此时数据库表里面订单表肯定存在一行数据，其中商品规格就是[C1, C1]。如果此时管理员想要增加一个新的规格C3，那怎么办？难道我们真的允许管理员可以操作吗？

我目前想法还是觉得不要支持商品编辑操作可能更好一点。一旦商品创建，而用户真的想要修改商品，那只能要求用户下架商品重新上架新商品。

或者仅仅支持用户修改一些基本内容，例如标题啊什么的。

**Comment by hhy464591454** [comment]
已经被订单关联的产品的主要属性是不能编辑更改的, 如果想将产品的规格/售价做更改等操作,建议再订单上做数据冗余,以免出现数据不对称的问题.

**Comment by zhongyusimon** [comment]
> 已经被订单关联的产品的主要属性是不能编辑更改的, 如果想将产品的规格/售价做更改等操作,建议再订单上做数据冗余,以免出现数据不对称的问题.

不是订单的数据，是购物车的数据。购物车里面还存在已下架的货品

**Comment by linlinjava** [comment]
这里我准备简化一下，商品目前已经存在一个is_on_sale字段，这里看后端是如何“删除”商品的：

（1） 如果是数据库逻辑删除或者物理删除商品，那么购物车查询商品时，发现商品不存在，则忽略或者删除购物车里面的记录。这样前端则看不到这些已经删除的商品了。

（2）如果后端是下架商品，也就是in_on_sale设置false，则购物车商品里面会显示。但是购物车里面已经下架的商品会不能选择，同时出现一个按钮，允许用户清楚已经下架的商品。

**Comment by linlinjava** [comment]
更新商品，以及购物车商品更新，请看 #293
