### ISSUE TITLE
订单确认页优惠券问题

### ISSUE THREAD

**Issue by beaver383** [linlinjava/litemall#262]
1、存在多张重复领取的优惠券时，下单使用的优惠券不是列表选中的那张
2、有效期内但不适合当前订单的优惠券未显示

**Comment by linlinjava** [comment]
这里两个问题能不能给出再具体一点的重现步骤呢，例如如何生成优惠券，如何重复领取，如何未显示。谢谢啊。

**Comment by beaver383** [comment]
> 1、存在多张重复领取的优惠券时，下单使用的优惠券不是列表选中的那张

操作步骤：
1、管理后台添加优惠券，设置“每人限领”为3张
2、前端领取该优惠券3次，数据库中适当修改end_time以便区分
3、商品下单，订单确认页面弹出的优惠券列表可以显示刚才的3张优惠券，选择中间的一张，提交订单
4、切换到用户的优惠券列表，显示未使用2张、已使用1张，但上一步操作中选中使用的优惠券状态为未使用、显示已使用的是3张中的另外一张

原因分析：
下单优惠券选择操作传递的是couponId而不是userCouponId

> 2、有效期内但不适合当前订单的优惠券未显示

1、管理后台添加优惠券，设置“最低消费”为10元
2、前端领取该优惠券
3、找一款10元以下的商品下单，订单确认页显示“没有可用优惠券”，弹出的优惠券列表显示“暂无优惠券”、“不可使用优惠券”为0

似乎是该功能未实现
