### ISSUE TITLE
导入数据库文件报错

### ISSUE THREAD

**Issue by hoz296301703** [linlinjava/litemall#266]
依次导入数据库文件报错，没有反应，能教一下怎么处理吗？谢谢！
![image](https://user-images.githubusercontent.com/24410145/63906391-46756480-ca4a-11e9-95f3-ef7a2a6b428a.png)

**Comment by linlinjava** [comment]
其实真的不清楚navicat为什么报错，反正用的mysql workbench是可以的，或者直接使用命令行也行。

**Comment by ghostcode** [comment]
我的navicat导入成功
