### ISSUE TITLE
微信登录失败，41003

### ISSUE THREAD

**Issue by LeonPang** [linlinjava/litemall#267]
不是必现，有的人就不行有的就可以，几百个用户出现了十几个这种情况了，微信登录模块没改过逻辑，所以请问是为什么？谢谢

**Comment by linlinjava** [comment]
你看看失败的情况是不是用户名昵称有emoji符合造成的。如果是这样，那你需要设置数据库支持emoji。具体你可以百度看看，或者看看这 #119

**Comment by LeonPang** [comment]
非常感谢各位！
