### ISSUE TITLE
http://118.24.0.153:8080/#/login 登录界面访问不了，怎么回事

### ISSUE THREAD

**Issue by BigData-YC** [linlinjava/litemall#268]
![image](https://user-images.githubusercontent.com/47716603/64306948-045a9e80-cfc7-11e9-957e-18892f678f33.png)

**Comment by linlinjava** [comment]
云服务器的1g内存现在满足不了mysql+spring boot，所以暂时没有服务器运行程序。
请本地安装测试吧。
