### ISSUE TITLE
搜索关键字时,无结果

### ISSUE THREAD

**Issue by 95zz** [linlinjava/litemall#269]
在一类下婴童，服装中均有商品；搜索"衣服"关键字时,没有结果。

**Comment by linlinjava** [comment]
你好，现在的搜索非常简单，只是基于商品的关键字来匹配。所以搜索衣服没有结果，因为关键字里面就是没有。你可以把这里扩展一下，采用专门的搜索服务。

**Comment by 95zz** [comment]
嗯那
