### ISSUE TITLE
已付款并且已发货的订单，如果再收到付款回调，就会再次变成已付款状态

### ISSUE THREAD

**Issue by zhongyusimon** [linlinjava/litemall#271]
WxOrderService中，不能用

// 检查这个订单是否已经处理过
        if (OrderUtil.isPayStatus(order) && order.getPayId() != null) {
            return WxPayNotifyResponse.success("订单已经处理成功!");
        }

已付款并且已发货的订单，如果再收到付款回调，就会再次变成已付款状态。

**Comment by zhongyusimon** [comment]
可以做以下的修改。

public static boolean hasPayed(Order order) {
        return OrderUtil.STATUS_CREATE != order.getOrderStatus()
                && OrderUtil.STATUS_CANCEL != order.getOrderStatus()
                && OrderUtil.STATUS_AUTO_CANCEL != order.getOrderStatus();
    }

**Comment by staneychan** [comment]
其实你可以提交一个pull request给作者，作者就会验证并合并

**Comment by linlinjava** [comment]
谢谢啊
