### ISSUE TITLE
图标问题

### ISSUE THREAD

**Issue by jack1157693211** [linlinjava/litemall#278]
<van-goods-action-icon
        @click="addCollect"
        icon="star-o"
        :style="(goods.userHasCollect !== 0) ? 'color: #f7b444;':''" />
      <van-icon name="star" />

这里图标是搜藏⭐   但是 我这里显示的是一本📕图标

**Comment by beaver383** [comment]
似乎是vant调整了字体库名称

可以尝试修改
litemall-vue/src/assets/scss/iconfont/iconfont.css
中13行
vanIcon 为 vant-icon

**Comment by jack1157693211** [comment]
我把 vant 模块中的字符ttf 复制出来
litemall-vue/src/assets/scss/iconfont/iconfont.css中引用
src: url('./vant-icon-0bc654.ttf') format('truetype');

**Comment by linlinjava** [comment]
我建议你删除node_modules，然后重新install依赖库。

我这里没有问题，有可能是中间有一次更新了vant大版本，你没有重新install引起的。
