### ISSUE TITLE
非常需要War打包方式

### ISSUE THREAD

**Issue by bodekjan** [linlinjava/litemall#280]
这项目打包是个jar包，不过很多生产环境自己有nginx和tomcat，我这样小白也不太懂maven，所以转成war有一定困难，也不能为了跑这个jar把本来有的tomcat停掉... 各种纠结

**Comment by linlinjava** [comment]
其实对于你的需求，不需要war打包方式，这里也是满足的，打包出来的jar包是可执行文件，你直接运行即可。

1.  你需要修改litemall-all模块的application.yml文件里面的server.port。
    目前是8080端口，因此会和你电脑内的tomcat端口冲突，你可以修改其他端口就可以了。

2 . 然后修改其他模块的配置文件，从8080改成你的新端口。
