### ISSUE TITLE
 提点小建议

### ISSUE THREAD

**Issue by chenchunhuis** [linlinjava/litemall#288]
感谢作者辛勤的付出，但是我阅读源码之后，我个人感觉：
1.为了拆项目而拆项目，又不是微服务，拆了db这种不伦不类的项目，不知道目的何在
2.redis等缓存都没有使用，根本无法应用在生产环境
3.库存支付等方面的锁不够完善，高并发就会导致资损
4.个人感觉这个作者就是学院派的，在项目中用到各种技术，脱离了实际业务

不服的人，十年之后再看就明白了

**Comment by linlinjava** [comment]
>

> 感谢作者辛勤的付出，但是我阅读源码之后，我个人感觉：

也感谢你的建议和批评。

> 1.为了拆项目而拆项目，又不是微服务，拆了db这种不伦不类的项目，不知道目的何在

这里你可能只想到单体项目和微服务分布式项目两种，但是实际上我是想做一种尝试，有没有一种折中的项目或者说演进的项目？

首先单体项目当然可行，但是管理后台和用户平台打包在一起，其实也是有问题。可能好的做法是管理后台一套代码，用户平台一套代码，那样就是两个项目。

其次，微服务项目当然好，但是我觉得一个人开发微服务架构的项目可能没有那么简单，而且一个小微企业用不了这种架构也买不了很多云服务器。

所以，基于当前面向场景是小微企业，我准备是从单体项目出发逐步完善，后期可以切换到微服务架构，所以现在的项目架构或者技术选型可能处于两者之间。

core模块是一些核心业务非相关公共代码，这个你应该可以理解，作为jar包提供功能。
db模块你说不伦不类，我能理解，也许你也说的对。我之所以这么做，是有以下考虑：
（1）我觉得应用模块，例如wx-api模块或者admin-api模块，应该和数据库访bao问操作代码相互解耦。wx-api模块存放db相关代码当然可行（也是很多项目这么做的），但是从以后微服务架构或者其他安全考虑，可能一个独立的数据库访问模块可能也不错，所以我这里尝试了一下；
（2）当然这里也带来了一些问题，例如wx-api模块访问和数据库交互，admin-api模块和数据库交互，实际上是两个层面的交互，放在一起可能也是显得不伦不类画蛇添足。写代码时，我也有不爽感觉。不过目前还能运行，所以我暂时不会变化这种架构。

> 2.redis等缓存都没有使用，根本无法应用在生产环境

如果你仔细看readme，issue和pr，你就知道redis在当前项目下面的进展计划。
从你的角度考虑，当然一个免费直接商用级别的代码开源才是政治正确的开源。
不过无所谓，我有自己的开发计划，后面会不断完善。
而且多说一句，从小微企业场景出发，现在代码不使用redis也是可以的，自己写点代码把数据库的数据直接缓存在hashmap中就可以了。

> 3.库存支付等方面的锁不够完善，高并发就会导致资损

当然有问题，我也再思考怎么完善。如果你有好的建议，或者直接能够pr那更好了。

> 4.个人感觉这个作者就是学院派的，在项目中用到各种技术，脱离了实际业务

我不知道你有没有仔细看代码，还是说你对所有类似项目都这么评价的。
实际上我这里是从业务出发，而不是从技术学院派出发的。现在代码和文档的思路都是基于如何将当前代码开发完善成能真正商用的代码，因此使用的后端技术、小程序端技术和前端技术都是最简单的，也暂时不会使用高精尖技术；相反，都是一直在改BUG或者优化一些功能细节方面。
我希望最后的项目是技术简单、覆盖基础业务、架构清晰可拓展的项目。

> 
> 不服的人，十年之后再看就明白了

**Comment by zhangalex** [comment]
库存减扣那里的确需要加锁，并发上去后会出现超卖的情况。
