### ISSUE TITLE
Throw errors when mvn install.  Current code tag1.4.0

### ISSUE THREAD

**Issue by rubi** [linlinjava/litemall#294]
[ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for org.linlinjava:litemall:0.1.0: Could not transfer artifact org.springframework.boot:spring-boot-starter-parent:pom:2.0.4.RELEASE from/to central (https://repo.maven.apache.org/maven2): Connection reset and 'parent.relativePath' points at no local POM

**Comment by linlinjava** [comment]
cd litemall
mvn clean
mvn package

**Comment by rubi** [comment]
run mvn clean still exists the same problem.  like this below.

---------bash output ----------
mvn clean                                                         
[INFO] Scanning for projects...
Downloading from central: https://repo.maven.apache.org/maven2/org/springframework/boot/spring-boot-starter-parent/2.0.4.RELEASE/spring-boot-starter-parent-2.0.4.RELEASE.pom
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for org.linlinjava:litemall:0.1.0: Could not transfer artifact org.springframework.boot:spring-boot-starter-parent:pom:2.0.4.RELEASE from/to central (https://repo.maven.apache.org/maven2): Connection reset and 'parent.relativePath' points at no local POM @ line 9, column 13

**Comment by rubi** [comment]
resoled it.
