### ISSUE TITLE
重新写一个vue项目的前台页面，该怎么打包部署？

### ISSUE THREAD

**Issue by wql54** [linlinjava/litemall#296]
![问题描述图片](https://user-images.githubusercontent.com/45921109/68293410-d843c280-00c8-11ea-9e70-a65e9f0d1cad.jpg)

**Comment by linlinjava** [comment]
参考 ff10f89caac97d89179c9b2843f23fa24d9a860e

all模块的pom.xml会额外做两个事情
（1）拷贝litemall-admin的编译文件夹dist到litemall-all模块的resources/static目录下面，
         因此部署以后，就是http://122.51.199.160:8080/#/
（2）拷贝litemall-vue的编译文件夹dist到litemall-all模块的resources/static/vue目录下面，
         因此部署以后，就是http://122.51.199.160:8080/vue/index.html#/

当然这里原理都是把静态文件放到spring模块的static下面，这样tomcat就会自动分发。

实际上，作为前后端分离项目，vue的编译文件不一定部署在spring模块里面，可以单独部署，只要vue项目的静态编译文件中的后端地址设置正确的后端服务地址即可。
