### ISSUE TITLE
usertoken建议使用jwt生成

### ISSUE THREAD

**Issue by azuretttc** [linlinjava/litemall#298]
目前user的token不是完全无状态的，而是存在服务器的内存的Map中，无法支持分布式，建议改成jwt的无状态的token，这样可以支持分布式部署应用

**Comment by azuretttc** [comment]
代码已经更新了，之前没看到，抱歉

**Comment by HuhaStephen** [comment]
你好，我看到微信小程序和web端用的是同一套token机制，这样是不是不太合适，比如说微信小程序可能需要登录一次，就可以长时间使用，web端可能就不需要保持登录很长时间

**Comment by zhangalex** [comment]
user token 这里是有安全问题，如果黑客知道了你的JwtHelper中的SECRET 生成token的信息，那么是可以随意创建任何人的token的。可能需要将登录成功后的token放到数据库/redis中，以防止黑客创建任意的token。
