### ISSUE TITLE
登录提示403

### ISSUE THREAD

**Issue by MrLiKH** [linlinjava/litemall#3]

**Comment by linlinjava** [comment]
你好，目前有时是会提示403，是前后端代码的逻辑没有整理好，会在之后解决。

**Comment by linlinjava** [comment]
有人把管理员密码改了，现在重置好了。

**Comment by MrLiKH** [comment]
谢谢 ok


原始邮件
发件人:linlinjavanotifications@github.com
收件人:linlinjava/litemalllitemall@noreply.github.com
抄送:LKHlikaihua91@163.com; Authorauthor@noreply.github.com
发送时间:2018年3月29日(周四) 21:28
主题:Re: [linlinjava/litemall] 登录提示403 (#3)


有人把管理员密码改了，现在重置好了。
