### ISSUE TITLE
swagger

### ISSUE THREAD

**Issue by in-my-heart** [linlinjava/litemall#300]
请问为什么去掉了swagger的支持，然后代码还在为什么访问不了swagger-ui.html

**Comment by linlinjava** [comment]
之前是去掉了，不过后来有人又贡献了配置代码，所以我还是合并了。
你可以通过以下链接访问：http://122.51.199.160:8080/swagger-ui.html

不过，目前我对swagger还是持谨慎态度：
（1）真正的支持swagger，不仅需要swagger配置代码，还需要在项目controller代码加上相应的注解，因此需要额外的精力做这些事情，我不想花费这些时间；
（2）目前我觉得与其引入swagger，还不如维护好一个接口文档。虽然这个接口文档花费的精力和时间更多，但是我觉得写文档的过程是一种对业务的思考，同时这种文档也解耦了前后端开发者。前端需要什么接口，可以先和后端商量，然后双方一起完成文档和数据格式，接下来前后端可以并行开发，只要遵守之前制定的约定。相反，如果依赖swagger提供接口，那么实际上接口文档工作是推给了后端，这种情况下很可能是前端和后端说一声需求，然后后端写好代码通知前端，前端再使用swagger看接口，然后前端很可能会发现后端接口的相关文档不全，只是简单的数据格式而已，这样又需要喊上后端一起讨论接口，这么看似乎swagger虽然做好了接口但是并没有很好地做好工作（虽然不是swagger的锅）。

**Comment by in-my-heart** [comment]
谢谢你，小公司一个人维护文档还是很痛苦的事情。养成写注解的习惯。
