### ISSUE TITLE
litemall-admin 上线后图标丢失问题

### ISSUE THREAD

**Issue by ksharpy** [linlinjava/litemall#301]
![image](https://user-images.githubusercontent.com/18019452/69110656-5a16f100-0ab6-11ea-873f-a4db54a33668.png)

**Comment by beaver383** [comment]
要么是升级了依赖版本过高不兼容了，要么是改动了配置导致css编译结果异常

**Comment by linlinjava** [comment]
我这里没有问题，你重新cnpm install一下吧

**Comment by linlinjava** [comment]
我现在升级element到最新的2.12.0，也出现了你这里的问题。

我也看到有类似的issue在element中提及 https://github.com/ElemeFE/element/issues/15317。
但是这个issue已经被官方关闭的。

所以我现在也不清楚到底是element的issue，还是因为我采用的vue-element-admin框架不兼容新版本element原因。

**Comment by linlinjava** [comment]
经过分析，这可能是旧的vue-element-admin的配置不支持新版本element。
4.2.1版本的vue-element-admin升级element版本不会出现这个问题。

请更新litemall，现在把基于的vue-element-admin从3.9版本更新到了4.2版本，经测试error没有了。
