### ISSUE TITLE
cas的操作可能无效

### ISSUE THREAD

**Issue by Ariesssssssss** [linlinjava/litemall#302]
![image](https://user-images.githubusercontent.com/22016291/69127735-cb21cd00-0ae5-11ea-8c8d-672faa75952e.png)
可重复读级别的话order可能不会获取到最新读取的数据

**Comment by linlinjava** [comment]
嗯，是有可能。其实数据库这里的操作可能有点问题

**Comment by linlinjava** [comment]
6b5db0b9a319ac0ff910bbe2bae0c148e6d477c0
