### ISSUE TITLE
行政区域

### ISSUE THREAD

**Issue by cjcj125125** [linlinjava/litemall#303]
你好，刚好项目里面需要使用到行政区域，看了一下数据库没有这一块的数据，示例demo里面有的，能不能发一下？谢谢

**Comment by lich1n** [comment]
您好，我没有设置行政区域，能详细描述下发什么内容给您么，以下是我的ak，sk


Access Key Id:TYYXUIN65I7OGKGYA0MM
Secret Access Key:41Dw7LoFgnezqn7ndIK6QN419Zxx2dLbIz45vR8K





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"nochange_"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月26日(星期二) 下午3:14
收件人:&nbsp;"linlinjava/litemall"<litemall@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[linlinjava/litemall] 行政区域 (#303)




你好，刚好项目里面需要使用到行政区域，看了一下数据库没有这一块的数据，示例demo里面有的，能不能发一下？谢谢

**Comment by cjcj125125** [comment]
我找到了，谢谢啦，我就是要数据库行政单位，省市区这些数据
