### ISSUE TITLE
你好，我基于你这个项目弄了个PC端，共享小程序的数据库，同时重新整合独立出了Redis Moudle 和鉴权Moudle ，就是说我可以基于你之前的代码进行改造吧？自己完善一些东西，但不用作商业，纯属学习！ 开发整合完了也会提交到gitHub来

### ISSUE THREAD

**Issue by shitouyuan** [linlinjava/litemall#308]

**Comment by shitouyuan** [comment]
可以基于这个项目会重新加上PC端的第三方登录，公共附件上传功能，同时可能会基于你目前的小程序做一些改动迁移，变成多端小程序！  有时间希望改造成spring cloud，因为前期码代码有点繁琐，就想直接采用你目前这个项目进行改造学习！

**Comment by linlinjava** [comment]
不是很明白你的意思，如果想一起完善代码非常欢迎，如果自己想扩展成新的项目也完全没问题。

**Comment by shitouyuan** [comment]
嗯嗯！那就好，因为基于数据库的都用的你的项目代码做基础的！&nbsp; 先跟作者知会一下，到时会注明项目基础来源



---原始邮件---
发件人: "linlinjava"<notifications@github.com&gt;
发送时间: 2019年12月22日(周日) 晚上10:18
收件人: "linlinjava/litemall"<litemall@noreply.github.com&gt;;
抄送: "shitouyuan"<429393910@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [linlinjava/litemall] 你好，我基于你这个项目弄了个PC端，共享小程序的数据库，同时重新整合独立出了Redis Moudle 和鉴权Moudle ，就是说我可以基于你之前的代码进行改造吧？自己完善一些东西，但不用作商业，纯属学习！ 开发整合完了也会提交到gitHub来 (#308)



不是很明白你的意思，如果想一起完善代码非常欢迎，如果自己想扩展成新的项目也完全没问题。

**Comment by linlinjava** [comment]
我也是基本别的开源项目做的，MIT开源协议了解一下。
