### ISSUE TITLE
VUE 后台管理-商品编辑 tinymce 编辑器最大化时界面左侧重叠

### ISSUE THREAD

**Issue by Muscleape** [linlinjava/litemall#316]
VUE 后台管理-商品编辑 tinymce 编辑器最大化时界面左侧重叠；
编辑器最大化后，直接切换其他的功能，再打开商品编辑时，页面不能上下滚动了

![image](https://user-images.githubusercontent.com/16682039/71790337-dd8ea080-306a-11ea-82f9-8aeb68ff317b.png)

**Comment by linlinjava** [comment]
没有想法解决这个问题，你可以研究研究tinymce这个。
或者你可以取消这个最大化按钮，不允许用户最大化编辑器。
