### ISSUE TITLE
login请求正常返回数据，报错"登录连接超时（后台不能连接，请联系系统管理员）"

### ISSUE THREAD

**Issue by jenhaolee** [linlinjava/litemall#317]
login请求正常返回数据，报错"登录连接超时（后台不能连接，请联系系统管理员）"。
（1）本地测试部署，服务器前后端部署，两个环境。
（2）login访问均可达服务器，服务端返回完整数据为：
{
    "errno": 0,
    "data": {
        "adminInfo": {
            "nickName": "admin123",
            "avatar": "https://wpimg.wallstcn.com/f778738c-e4f8-4870-b634-56703b4acafe.gif"
        },
        "token": "603cfa90-e2b0-4847-a299-bc9f9426f3bb"
    },
    "errmsg": "成功"
}
（3）页面显示”登录连接超时（后台不能连接，请联系系统管理员）“，页面未跳转。

**Comment by Edisonhuxi** [comment]
怎么解决的
