### ISSUE TITLE
订单的submit问题

### ISSUE THREAD

**Issue by 6freeair2016** [linlinjava/litemall#33]
由于订单id生成是自增的，而订单提交开启事务了，所以订单还未生成时就去获取订单id获取的结果位空

**Comment by linlinjava** [comment]
额，不明白你的意思。现在代码可以正常工作，订单会自动生产。

你的代码是不是以前的，之前好像有这个问题，但是已经修复了。

这里我关闭这个issue。如果你觉得还是有问题，或者可以补充详细细节，可以在打开这个issue。
