### ISSUE TITLE
登录后台用户名密码admin123提示不正确

### ISSUE THREAD

**Issue by swmonoku** [linlinjava/litemall#338]
ubuntu 16.04  mysql 5.7  配置deploy后可以访问后台管理页面，但是登录的时候提示admin123用户名或密码不正确是什么原因啊

**Comment by linlinjava** [comment]
不清楚，你可以看看前端页面链接地址是否正确，数据库数据是否正确。
总之，多测试或者DEBUG吧。

**Comment by swmonoku** [comment]
> 不清楚，你可以看看前端页面链接地址是否正确，数据库数据是否正确。
> 总之，多测试或者DEBUG吧。

感谢回复，想请问下，登录的日志在哪里看啊？

**Comment by leopku** [comment]
登录后，后台返回的 perms 为空

store/modules/user.js
```
          if (data.perms && data.perms.length > 0) { // 验证返回的perms是否是一个非空数组
            commit('SET_PERMS', data.perms)
          } else {
            reject('getInfo: perms must be a non-null array !')
          }
```

**Comment by flashcloud** [comment]
我也遇到同样的情况，在“litemall-admin-api/src/main/java/org/linlinjava/litemall/admin/web/AdminAuthController.java”类的"public Object info()"设置断点跟踪发现“Integer[] roleIds = admin.getRoleIds();”roleIds的值为空，在后台数据库发现对应的表“litemall_role”为空，原来是在从sql文件“litemall-db/sql/litemall_data.sql”导入数据时未能全部导入。再次执行数据库重建及数据导入后，就能成功登录后台
