### ISSUE TITLE
导出订单

### ISSUE THREAD

**Issue by chengdada123** [linlinjava/litemall#339]
1、导出订单内容比较少，不利于统计，可否增加详细的列，比如用户订购的商品明细，数量，金额，快递公司、单号信息等，便于核对和汇总订单。
2、订单管理菜单中的过滤选项是否可以添加起止时间搜索。
3、可否支持批量发货的功能，也就是通过用Excel按照模板上传后批量录入对应订单的物流公司和单号实现批量发货。
祝项目越来越好。

**Comment by chengdada123** [comment]
1、导出订单内容可否管理员自主选择导出哪些列。

**Comment by linlinjava** [comment]
1, 订单导出内容再多一点，后面会完善；
2. 订单基于时间的过滤，后面也会完善；
3. 批量发货不会实现，这个项目本身只会实现基本的业务，更高级的业务请自行开发；
4. 导出列可选择不会实现，原因同3。

**Comment by linlinjava** [comment]
2. 基于订单时间的过滤， 5e0bd4c0af85021260b1921abb441bf5d87a2d40

**Comment by chengdada123** [comment]
经测试，有时间过滤的菜单，实际上起不到过滤的效果。

**Comment by linlinjava** [comment]
请给出重现步骤，目前的时间过滤是指订单创建时间

**Comment by chengdada123** [comment]
![TIM截图20200213120203](https://user-images.githubusercontent.com/59160585/74400437-d7a19180-4e58-11ea-9412-d9c6bb3b9417.jpg)
订单有69个，无论时间如何选择，比如这些订单都是之前的，选昨天和今天也显示这个69个订单。

**Comment by chengdada123** [comment]
![TIM截图20200213130100](https://user-images.githubusercontent.com/59160585/74403041-f015aa00-4e60-11ea-9845-3c48bc76ae58.jpg)

**Comment by linlinjava** [comment]
http://122.51.199.160:8080/#/mall/order
你可以看看演示平台效果，里面三个订单是最近的

**Comment by linlinjava** [comment]
再次明确一下，这里的时间过滤添加中的时间指的是订单下单时间，不是支付时间。
如果需要支付时间或者其他时间，你可以调整一下代码。

**Comment by chengdada123** [comment]
我库里下单时候也是不一样，就是起不到过滤的作用，看日志，也没有where add_time的记录。请问大佬除了更新了4个文件还需要调整哪里吗？

**Comment by chengdada123** [comment]
[ERROR] /home/litemall/litemall-db/src/main/java/org/linlinjava/litemall/db/service/LitemallOrderService.java:[203,14] cannot find symbol
  symbol:   method setAftersaleStatus(java.lang.Short)
  location: variable order of type org.linlinjava.litemall.db.domain.LitemallOrder

**Comment by linlinjava** [comment]
你可以看看最近提交了多次代码，主要实现了简单的售后功能，数据库是新增了litemall_aftersale表，以及订单litemall_order表里面增加aftersale_status字段。
