### ISSUE TITLE
有水平越权漏洞？

### ISSUE THREAD

**Issue by XiaomingX** [linlinjava/litemall#341]
/**
	 * 用户收货地址列表
	 *
	 * @param userId 用户ID
	 * @return 收货地址列表
	 */
	@GetMapping("list")
	public Object list(@LoginUser Integer userId) {
		if (userId == null) {
			return ResponseUtil.unlogin();
		}
		List<LitemallAddress> addressList = addressService.queryByUid(userId);
		return ResponseUtil.okList(addressList);
	}

**Comment by linlinjava** [comment]
非常感谢你的建议。
对于你这里的list则是不存的，因为userId不是前端传过来的，而是后端基于token自动转换的，因此不会存在这个问题。
但是某些情况下，则是存在这个问题。
例如
```
    @PostMapping("delete")
    public Object delete(@LoginUser Integer userId, @RequestBody String body) {
```
这里原来逻辑是从body中解析前端参数id，然后delete。但是这里没有校验id所对应的数据项是当前userId的，因此存在问题。现在已仔细审查并解决。
