### ISSUE TITLE
HTTP Status 400 – Bad Request

### ISSUE THREAD

**Issue by asdf12343800** [linlinjava/litemall#355]
我本地编译出了litemall-all-0.1.0-exec.jar，然后放到阿里云服务器上，服务器是centos，通过nginx转发，我在application.yml里设置端口9012，nginx转发到9012，在浏览器里访问nginx域名/admin/index/index，返回HTTP Status 400 – Bad Request，请问这个怎么解决，或者怎么查看java访问日志

**Comment by linlinjava** [comment]
这里自己多实践一下
