### ISSUE TITLE
用 Taro跨端框架实现了小程序端和 h5端，能否Readme加个推荐

### ISSUE THREAD

**Issue by jiechud** [linlinjava/litemall#356]
[Taro_Mall](https://github.com/jiechud/taro-mall)是一款多端开源在线商城应用程序，后台是基于litemall基础上进行开发，前端采用Taro框架编写，现已全部完成小程序和h5移动端，后续会对APP，淘宝，头条，百度小程序进行适配。Taro_Mall已经完成了 litemall 前端的所有功能

地址：https://github.com/jiechud/taro-mall

![image](https://user-images.githubusercontent.com/9709396/75883293-c2b78d00-5e5d-11ea-8eff-e79dbd3dede5.png)

**Comment by linlinjava** [comment]
已加
