### ISSUE TITLE
商品上架-商品库存建议修改一下展示

### ISSUE THREAD

**Issue by BigdataEdison** [linlinjava/litemall#364]
<img width="1125" alt="goods" src="https://user-images.githubusercontent.com/17466742/77251055-0ea06980-6c87-11ea-97d2-c302971b40c9.png">

1.  在商品规格比较多的情况，每一种规格的售价和数量都不一样
2. 每一种规格，都希望可以单独进行设置

**Comment by linlinjava** [comment]
这里商品规格的设置页面效果设计的不是很好，所以可能给你造成了误解。
你这里的使用方式是有问题的。

你应该这样设置：
1. 添加一个规格：规格名是“颜色”，规格值是：“红色”；
2. 添加一个规格：规格名是“颜色”，规格值是：“黑色”；
3. 添加一个规格：规格名是“尺寸”，规格值是：“L”；
4. 添加一个规格：规格名是“尺寸”，规格值是：“S”；

这个时候你再看库存设置页面的效果就变成了：
“红色” - “L”     0
“红色” - “S”     0
“黑色” - “L”     0
“黑色” - “S”     0
 
以上是多规格的配置效果。

如果你只需要配置单规格，那你可以这样做
1. 添加一个规格：规格名是“规格”，规格值是：“洗脸巾 20边”；
2. 添加一个规格：规格名是“规格”，规格值是：“洗脸巾 40边”；
3. 添加一个规格：规格名是“规格”，规格值是：“洁面巾 20边”；
4. 添加一个规格：规格名是“规格”，规格值是：“洁面巾 40边”；

这个时候你再看库存设置页面就变成了：
“洗脸巾 20边”     0
“洗脸巾 40边      0
“洁面巾 20边”     0
“洁面巾 40边”     0

**Comment by BigdataEdison** [comment]
@linlinjava  thank you very much ! I am GET !
