### ISSUE TITLE
支持Docker部署

### ISSUE THREAD

**Issue by linlinjava** [linlinjava/litemall#37]

**Comment by zhangalex** [comment]
请问是否需要PR？我刚好做了一个demo。

**Comment by duanhongyi** [comment]
docker部署是不是另外起一个项目更好？比如说litemall-docker

**Comment by zhangalex** [comment]
不需要吧，就把dockerfile丢在litemall-all里。

**Comment by shougao** [comment]
> 请问是否需要PR？我刚好做了一个demo。

把pull request贴出来吧，如果没有merge的话，我们也能使用，使用docker-compose.yml的方式做的吗？

**Comment by linlinjava** [comment]
现在pr里面有个，但是基于以前的。

如果你们有现成的，也可以再来一个pr，我看看，实践一下，谢谢。

**Comment by linlinjava** [comment]
简单支持 7fa617631cd471bb53c1d529bbd7a12309fa0129
后续还会继续实践完善
