### ISSUE TITLE
[BUG]: logicalDeleteValue in generatorConfig.xml should set to "true" instead of "1" 

### ISSUE THREAD

**Issue by dannyZhou** [linlinjava/litemall#372]
logicalDeleteValue in generatorConfig.xml should set to "true" instead of "1" 
logicalUnDeleteValue in generatorConfig.xml should set to "false" instead of "0" 

![image](https://user-images.githubusercontent.com/6329191/79689908-5fa57c80-828a-11ea-9f10-e11cfda8e66c.png)

Refs: https://blog.csdn.net/u013379717/article/details/102615126

**Comment by linlinjava** [comment]
谢谢你的issue，这里deleted使用的是一个插件生成的相关代码，目前看起来运行是正常的。
最后数据库里面deleted是0或者1，0则是未删除，1则是删除。
虽然不清楚为什么你这里图片看起来似乎是说明deleted使用上语义有问题，不过因为目前运行
没问题，所以我不准备过多研究。
