### ISSUE TITLE
页面访问报错，找不到组件

### ISSUE THREAD

**Issue by xy0514** [linlinjava/litemall#373]
![image](https://user-images.githubusercontent.com/48755622/79832135-5841b880-83db-11ea-82ca-bc5c39e962aa.png)

**Comment by wuyangjin** [comment]
我的也提示这个,奇怪了

**Comment by xunyegege** [comment]
估计是什么依赖更新了，我也报这个错

**Comment by tx123456** [comment]
我也遇到这个问题了，求解决方案

**Comment by algernoonLiu** [comment]
有解决了的吗

**Comment by wuyangjin** [comment]
群里有解决方案，是懒加载的问题https://github.com/PanJiaChen/vue-element-admin/issues/3127（参考这个链接）

**Comment by zhangliangnbu** [comment]
> 群里有解决方案，是懒加载的问题[https://github.com/PanJiaChen/vue-element-admin/issues/3127（参考这个链接）](https://github.com/PanJiaChen/vue-element-admin/issues/3127%EF%BC%88%E5%8F%82%E8%80%83%E8%BF%99%E4%B8%AA%E9%93%BE%E6%8E%A5%EF%BC%89)

能否麻烦下把解决方案搬到这个issue里？让大家都看下，很多人估计都不怎么上QQ。。。

**Comment by wuyangjin** [comment]
国外大佬已经解决了,重新cnpm install一下就ok了

**Comment by linlinjava** [comment]
解决那就close了
