### ISSUE TITLE
删除一级分类会导致该一级分类下的二级分类看不到

### ISSUE THREAD

**Issue by wlnirvana** [linlinjava/litemall#376]
例如通过管理后台将范例数据中的“居家”分类删除后，“布艺软装”等二级分类虽然在数据库中仍然未被标记为删除，但无法通过管理后台看到、修改。

**Comment by linlinjava** [comment]
这里，你可以根据自己业务需要进一步优化。
通常由两种做法：
一种是，如果二级分类存在，则删除一级分类会失败；
另外一种是，如果删除以及分类，则自动删除二级分类。

此外，还存在一个问题，即有些商品以及关联到分类了。
那么此时删除分类是否允许。
例如，分类“A"下面已有商品，则可能应该拒绝删除分类A的操作。
