### ISSUE TITLE
后台登录不进去

### ISSUE THREAD

**Issue by WoodyWoodyLee** [linlinjava/litemall#378]
admin123失效，不知道是什么原因
![批注 2020-04-28 235157](https://user-images.githubusercontent.com/33867635/80509026-63807f80-89ab-11ea-8ad2-21fa190d2829.png)

**Comment by linlinjava** [comment]
对不起，忘了演示平台限制修改密码了。
可能有人把密码修改了。
现在应该可以了

**Comment by WoodyWoodyLee** [comment]
谢谢~~~
