### ISSUE TITLE
litemall-admin所基于的vue-element-admin跟新

### ISSUE THREAD

**Issue by linlinjava** [linlinjava/litemall#38]

**Comment by AloneWeb** [comment]
可以给一个现在用的vue-element-admin版本号吗？这个应该需要对照vue-element-admin更新日志去更新了

**Comment by linlinjava** [comment]
vue-element-admin 3.6.2

**Comment by linlinjava** [comment]
目前更新至3.9.3， 6f0ebe3e1f73df304e7936772c50570e1c4f474e

**Comment by linlinjava** [comment]
目前更新至4.2.1
