### ISSUE TITLE
微信小程序首页点击广告轮播图 活动链接怎么跳转？

### ISSUE THREAD

**Issue by IT-moke** [linlinjava/litemall#383]
![image](https://user-images.githubusercontent.com/50235547/81247654-22dcd200-904d-11ea-9b30-d07fbecbf279.png)
@duanhongyi

**Comment by linlinjava** [comment]
你可以看一下代码，目前管理后台填写一个商品id，这样前端点击链接可以跳转商品详情。
当然，你可以改成你需要的其他场景
