### ISSUE TITLE
docker部署之后无法登陆，显示404

### ISSUE THREAD

**Issue by schizobulia** [linlinjava/litemall#384]
根据docker文档部署，但登陆时显示404

很奇怪的一句话 [地址](https://github.com/linlinjava/litemall/tree/master/docker#%E9%A1%B9%E7%9B%AE%E6%89%93%E5%8C%85)
```
修改litemall文件夹下面的*.yml外部配置文件，当litemall-all模块启动时会 加载外部配置文件，而覆盖默认jar包内部的配置文件。 例如，配置文件中一些地方需要设置成远程服务器的IP地址
```
上面这句话中：出现  例如、配置文件中的一些地方... 这种话
为什么不明确指出呢？难道需要部署的人去猜？

**Comment by linlinjava** [comment]
你奇怪，我也奇怪。
这里的口气是责怪吗，还是讨论？

如果是责怪，嫌弃文档写的不好，那就不要看好了，谢谢。

如果想要讨论，请仔细看一下自己说的话，拿出你平时和同学、同事以及老师讨论时说话的口气，谢谢。代码会写错，文档会不清楚，请给予一点理解和帮助。

本项目甚至文档只是一种参考实现，部署可以有多种方式。
你可以不需要使用这种外部配置文件，而直接在项目内部的配置文件写上自己部署阶段的配置信息。

这里采用外部配置文件只是一种某种实践，因为我个人觉得内部配置文件写上部署阶段信息或者上线阶段信息可能会不安全，因为这些一般会push到git仓库，而采用外部配置则可以放在其他文件夹，不需要push到仓库中。而具体在外部文件配置什么信息来覆盖内部文件文件中的信息，是取决于开发者自己的需要。我觉得没有必要写得那么清楚。而且我认为一个开发者也应该熟悉代码以及配置的信息，因此开发者自己应该有能力来确定应该写什么，或者采用其他配置方案，他不需要猜。
