### ISSUE TITLE
发现的几个小问题反馈

### ISSUE THREAD

**Issue by luhongbin** [linlinjava/litemall#385]
1.库上传图片默认设置1M之内，没有参数供修改。application.yml添加参数spring.servlet.multipart.max-file-size: 20MB仍然无效。

**Comment by luhongbin** [comment]
2.小程序联系客服，代码不执行，提示联系客服会话：sessionFrom:weapp

**Comment by luhongbin** [comment]
3.商品管理，规格一旦新建之后，没有增加修改删除名称的动作，很不方便。

**Comment by luhongbin** [comment]
4.小程序，优惠券全部删除之后，新客户还有出现个兑换优惠券的内容

**Comment by luhongbin** [comment]
> 1.库上传图片默认设置1M之内，没有参数供修改。application.yml添加参数spring.servlet.multipart.max-file-size: 20MB仍然无效。

这个官方解决了

**Comment by linlinjava** [comment]
> 2.小程序联系客服，代码不执行，提示联系客服会话：sessionFrom:weapp

你看一下官方文档，了解一下客服怎么用，小程序这里前后端无需任何配置。

至于你没有效果，应该是在体验版和正式版才能使用，开发版是不行的。

**Comment by luhongbin** [comment]
非常感谢您的回复

**Comment by luhongbin** [comment]
广告管理的活动链接怎么写，文档中没有说明，我想显示一个产品

**Comment by heliangtmac** [comment]
广告配置商品id实现跳转
