### ISSUE TITLE
现在用的是快鸟物流，微信已经为小程序提供了微信物流，免费，能否修改

### ISSUE THREAD

**Issue by luhongbin** [linlinjava/litemall#389]
https://developers.weixin.qq.com/miniprogram/dev/api-backend/open-api/express/by-business/logistics.addOrder.html

能否改成微信官方提供的物流公司，多个选择，毕竟是在微信平台搞的小程序系统

**Comment by linlinjava** [comment]
没有时间完成，自行研究吧。
如果能够贡献PR更好了。
