### ISSUE TITLE
发现的几个小问题

### ISSUE THREAD

**Issue by yoalley** [linlinjava/litemall#391]
1，小程序端，申请售后，一直弹窗，提交中
2，小程序端，评价按钮不可按

**Comment by alisdk** [comment]
有这框架已经很好了，有BUG自己改改吧。已经节省80%的劳力成本了。

**Comment by xiaorui16888** [comment]
> 有这框架已经很好了，有BUG自己改改吧。已经节省80%的劳力成本了。

你这话说的，人家提交几个小问题。都不可以了吗？
