### ISSUE TITLE
litemall-admin 不知道部署在服务器需要注意什么 

### ISSUE THREAD

**Issue by yuhe520521** [linlinjava/litemall#392]
我根据vue的教程 把admin 的vue 代码  打包 将 dist 文件 上传到服务器  完全访问不了 我不是vue程序员  java接口没问题 但是 vue的管理端怎么都跑不了 不知道 admin的部署 需要上传哪些文件 或者需要修改什么配置参数嘛? 请教大神.

**Comment by yuhe520521** [comment]
本地跑没有问题 就是服务器部署不了

**Comment by getideas** [comment]
node.js装了吗？

**Comment by yuhe520521** [comment]
> node.js装了吗？

装了  环境应该没有问题 我用的是宝塔的服务器   我应该是属于不会部署,部署的不对,网上的教程感觉都不适用于 litemall-admin的项目  没有main.js .而且  index.html  路径在dist里面我也没本事移出来 .因为我不是前端开发者  vue 对我来说也是新语言  一脸懵逼 .我在本地跑的好好的,我能把整个项目传到服务器 在服务器上用本地的运行方式跑吗 ?我试过一次  cnpm run dev 运行过以后 外网的地址直接没有出来,只有localhost有 而且还没有端口,我有点懵逼到底是服务器环境问题 还是我部署不对.

**Comment by linlinjava** [comment]
建议你可以看看vue-element-admin这个项目或者百度一些资料，了解一下vue前端项目怎么部署。
其实很简单，vue项目编译得到dist静态文件，部署到nginx或者tomcat下就可以了。

本项目就是利用了一点脚本把litemall-admin下面的编译静态文件自动打包到litemall-all项目的static目录下面。因为是嵌入书的tomcat，因此static下面的静态文件就自动对外服务。

**Comment by linlinjava** [comment]
宝塔方式的部署没有实践过，因此可能这里会有些问题。
建议你先看看本项目的文档，了解一下本项目怎么部署的，后面了解细节了再利用宝塔部署吧。
