### ISSUE TITLE
新增砍价等推广功能

### ISSUE THREAD

**Issue by allanwxl** [linlinjava/litemall#393]

**Comment by allanwxl** [comment]
小商户还是推广比较难

**Comment by linlinjava** [comment]
不会实现。

恰恰相反，本项目想做的只是简单的小商城，是普通的线下小店到线上，部署时仅仅需要一个云服务器即可。

因此小店真正地推广应该是利用自身特色业务或者使用场景来吸引客户到线上付款即可，而不是采用互联网式的一些推销技术。

当然，你可以参考代码实现自己需要的推销功能。
