### ISSUE TITLE
是否搞一个gradle版本的,maven真心太难受

### ISSUE THREAD

**Issue by s949492225** [linlinjava/litemall#4]
这项目真不错,支持,支持,手机版有计划吗

**Comment by linlinjava** [comment]
你好，目前开发计划是:

1. 微信小程序优化
2. 管理后台重新设计
3. 安全及系统相关功能完善

有兴趣可以一起做，自己也仅仅想做一个完整可用的项目。

gradle的不了解，如果懂得话可以麻烦来一个：）

**Comment by s949492225** [comment]
我也是比较忙,所以还没办法帮你,不过咱们可以加个好友

**Comment by linlinjava** [comment]
额，我觉得微信qq之类的信息需要同步在线交流可能比较难，而且重要信息很容易丢失，目前准备采用Issue异步交流想法和技术，同时也能查找。
