### ISSUE TITLE
litemall-db/litemall_table.sql和litemall_data.sql 建议声明schema方便SQL Workbench导入

### ISSUE THREAD

**Issue by chengNeil** [linlinjava/litemall#401]
Suggest to add the following at top of sql:

CREATE DATABASE IF NOT EXISTS litemall ;
USE litemall;

**Comment by linlinjava** [comment]
如果你仔细看litemall-db的文件夹，可以发现litemall_scheme.sql.
通常，在workbench中先运行litemall_scheme.sql就可以。
