### ISSUE TITLE
我把application.yml里面的tencent->appid改成自己的微信appid系统就出错了

### ISSUE THREAD

**Issue by chengNeil** [linlinjava/litemall#402]
”public static class Tencent“ 里面的appid是private int， 我觉要改成private String，因为微信的appid type都是String，感觉不能存近int。我把application.yml里面的tencent->appid改成自己的微信appid系统就出错了。麻烦大师看看这个问题

**Comment by chengNeil** [comment]
/\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v2.1.5.RELEASE)

09:29:53.024 logback [main] INFO  org.linlinjava.litemall.Application - Starting Application v0.1.0 on Neils-MacBook-Air.local with PID 5475 (/Users/neilhe/minimall/litemall-all/target/litemall-all-0.1.0-exec.jar started by neilhe in /Users/neilhe/minimall)
09:29:53.029 logback [main] DEBUG org.linlinjava.litemall.Application - Running with Spring Boot v2.1.5.RELEASE, Spring v5.1.7.RELEASE
09:29:53.030 logback [main] INFO  org.linlinjava.litemall.Application - The following profiles are active: db,core,admin,wx
09:29:59.763 logback [main] ERROR o.s.b.d.LoggingFailureAnalysisReporter - 

***************************
APPLICATION FAILED TO START
***************************

Description:

Failed to bind properties under 'litemall.notify.sms.tencent.appid' to int:

    Property: litemall.notify.sms.tencent.appid
    Value: “这里显示的是我的微信APPID”
    Origin: class path resource [application-core.yml]:42:16
    Reason: failed to convert java.lang.String to int

Action:

Update your application's configuration

**Comment by linlinjava** [comment]
请仔细搞清楚腾讯云短信appid和你的商城小程序appid

**Comment by chengNeil** [comment]
感谢，两个appid我搞混；
