### ISSUE TITLE
MySQL 连接驱动依赖 升级后丢失Stringutiils

### ISSUE THREAD

**Issue by youaremywind** [linlinjava/litemall#413]
MySQL 连接驱动依赖 升级到1.8 StringUtils没有了 代码需要更新，导入新的
![微信图片_20200704124322](https://user-images.githubusercontent.com/18423358/86505234-b8e66c00-bdf4-11ea-97f9-4a93491dbdb6.png)

**Comment by linlinjava** [comment]
谢谢提醒，已fix
