### ISSUE TITLE
修改application-db.yml后不生效

### ISSUE THREAD

**Issue by zhqinux** [linlinjava/litemall#424]
我的数据库是单独的一台电脑
我修改了application-db.yml后，mvn spring-boot:run 启动时报错
我看报错信息是数据库连接池仍然在尝试连接localhost:3306

请教一下这是怎么回事，数据库连接地址除了application-db.yml外还由其他地方需要设置吗？

**Comment by linlinjava** [comment]
你可以搜一下3306的地方，在deploy目录下面也有，但是不应该影响你这里。
