### ISSUE TITLE
微信登陆间隔几个小时打开需要重新登陆

### ISSUE THREAD

**Issue by singworld** [linlinjava/litemall#426]
间隔几个小时重新打开需要重新登陆   请问这是可配置的
还是异常情况

环境：个人资质小程序

**Comment by zhanglei829** [comment]
登录状态是用jwt的形式保持的，默认是2h过期。可以在下面截图中位置，修改过期时间：
![image](https://user-images.githubusercontent.com/40270286/91048673-90d5f500-e64e-11ea-8139-967f7427321a.png)

**Comment by singworld** [comment]
感谢
