### ISSUE TITLE
自定义iconfont在哪里管理的呢  怎么查看

### ISSUE THREAD

**Issue by peiyijiao** [linlinjava/litemall#439]
自定义iconfont在哪里管理的呢  怎么查看

**Comment by linlinjava** [comment]
建议可以百度一下，比如 https://blog.csdn.net/qq_32113629/article/details/79740949

**Comment by linlinjava** [comment]
https://panjiachen.gitee.io/vue-element-admin-site/zh/feature/component/svg-icon.html
