### ISSUE TITLE
wx-api 怎么启动

### ISSUE THREAD

**Issue by wendyayang** [linlinjava/litemall#442]

**Comment by wendyayang** [comment]
wx-api怎么启动呀
![image](https://user-images.githubusercontent.com/43986800/98694636-a7b5f900-23ac-11eb-94c5-e47da5214101.png)

**Comment by linlinjava** [comment]
看文档。通常运行litemall-all模块启动后端服务，运行litemall-wx启动小程序前端，运行litemall-admin启动管理后台前端。
