### ISSUE TITLE
商品详情判断只有一个货品默认选中时valueList属性报错

### ISSUE THREAD

**Issue by WesinZ** [linlinjava/litemall#443]
部分代码如下
`let _specificationList = res.data.productList;
        let _tmpPicUrl = res.data.productList[0].url;
        //console.log("pic: "+_tmpPicUrl);
        // 如果仅仅存在一种货品，那么商品页面初始化时默认checked
        if (_specificationList.length == 1) {
          if (_specificationList[0].valueList.length == 1) {
            _specificationList[0].valueList[0].checked = true

            // 如果仅仅存在一种货品，那么商品价格应该和货品价格一致
            // 这里检测一下
            let _productPrice = res.data.productList[0].price;
            let _goodsPrice = res.data.info.retailPrice;
            if (_productPrice != _goodsPrice) {
              console.error('商品数量价格和货品不一致');
            }

            that.setData({
              checkedSpecText: _specificationList[0].valueList[0].value,
              tmpSpecText: '已选择：' + _specificationList[0].valueList[0].value
            });
          }
        }`

查了下服务端代码，返回实体并没有这个valueList，js这边直接拿着用，所以undifine

**Comment by linlinjava** [comment]
已经修复
