### ISSUE TITLE
是否可以需要预约功能

### ISSUE THREAD

**Issue by jsRuner** [linlinjava/litemall#451]
非常感谢，我计划贡献代码，但是可能是功能性代码，
例如我的实际需求是需要实现一个  微信预约。不知道是否需要该功能，需要的话，我将提交一份

**Comment by linlinjava** [comment]
我不会再开发提交功能性的代码，但是如果有贡献的功能性代码，而且是完整合理地，我非常欢迎。
我也可以直接白嫖。谢谢。

**Comment by jsRuner** [comment]
好的。了解了。我会贡献的。非常感谢你能搭建如此棒的项目。
