### ISSUE TITLE
新的小商场前端 litemall-renard

### ISSUE THREAD

**Issue by linlinjava** [linlinjava/litemall#46]
当前项目的litemall-wx小程序前端和扫码上线实例小程序效果不一致，这里是因为由menethil开发，目前未开源。
是否开源不一定。

**Comment by AloneWeb** [comment]
@linlinjava 您好，我想问下这是个什么样的前端? 有详细的介绍吗?

**Comment by linlinjava** [comment]
你好，就是readme里面的上线实例，你可以扫一扫看看。

**Comment by linlinjava** [comment]
已经上传上线小商船renard代码，在renard-wx目录下面。

所以目前本项目会存在两套小商场前端。
