### ISSUE TITLE
微信小程序登录的时候没有获取用户绑定的手机号码

### ISSUE THREAD

**Issue by liangsongliu** [linlinjava/litemall#462]
微信小程序登录的时候没有获取用户绑定的手机号码，该功能是否考虑增加？？

**Comment by longmain** [comment]
没有必要。
从UE角度应该让使用过程尽量顺滑。同时，小程序应尽量少获取客户信息，用不到的信息尽量不要获取。
另外，请参考以下commit：
git log --stat 749e6ab251e965147e6af1f03fb4956add28da97

**Comment by linlinjava** [comment]
的确，从微信小程序审核角度出发，不允许开发者过度请求用户的信息。
电话号码应该在其他必要场景引导用户绑定手机号码。
