### ISSUE TITLE
NullPointerException 异常 没有处理

### ISSUE THREAD

**Issue by yutimothy666** [linlinjava/litemall#466]
出现NullPointerException 异常直接会导致前端卡住

**Comment by linlinjava** [comment]
正常页面内部如果后端有NullPointerException ，前端会收到异常信息，同时显示后端内部异常的报错信息。

![image](https://user-images.githubusercontent.com/4223779/111059044-8e919600-84cd-11eb-8e8f-944b8a4091ee.png)
