### ISSUE TITLE
真机调试和预览模式下 wx.switchTab 登录跳转问题

### ISSUE THREAD

**Issue by MaidongAndYida** [linlinjava/litemall#476]
微信账号登录或者账号密码登录成功后，wx.switchTab 跳转到tabbar的时候，会再次跳转到选择登录方式的界面，而不是用户个人信息页，请问这是什么原因？

**Comment by MaidongAndYida** [comment]
这个问题我找到原因了,是@LoginUser这个注解没有起作用,即LoginUserHandlerMethodArgumentResolver没有起到作用,还没找到为什么没有起到参数拦截的作用呢,debug也进不去

**Comment by linlinjava** [comment]
https://gitee.com/linlinjava/litemall/issues/I3I94X

使用Lazy注解
