### ISSUE TITLE
litemall-vue工程中页面header存在title监听异常，

### ISSUE THREAD

**Issue by fyj0846** [linlinjava/litemall#485]
工程中litemall/litemall-vue/src/store/index.js中，未预设title属性，导致vue无法准确监听变化，现象为header的title更新错误。

源码：
const state = {
  showHeader:true,
}

修复方案：
const state = {
  showHeader:true,
  title:''      //  ---> 增加此属性
}

**Comment by linlinjava** [comment]
17bbd6c1d872bfc7e4426615205244b3caa44de7
