### ISSUE TITLE
Failed to start LSB: litemall-all

### ISSUE THREAD

**Issue by hjf-codecrazy** [linlinjava/litemall#517]
根据单机单服务部署文档部署
执行
`sudo service litemall start`
发现报错，报错如下：
`Job for litemall.service failed because the control process exited with error code. See "systemctl status litemall.service" and "journalctl -xe" for `details.`
`
根据提示我在输入systemctl status litemall.service
提示如下：
`
 litemall.service - LSB: litemall-all
   Loaded: loaded (/etc/init.d/litemall; bad; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2022-07-20 23:16:59 CST; 1min 58s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 24220 ExecStart=/etc/init.d/litemall start (code=exited, status=1/FAILURE)

Jul 20 23:16:59 iZbp1c8cdf0fuf0q0f6tekZ systemd[1]: Starting LSB: litemall-all...
Jul 20 23:16:59 iZbp1c8cdf0fuf0q0f6tekZ litemall[24220]: Application is running as root (UID 0). This is considered insecure.
Jul 20 23:16:59 iZbp1c8cdf0fuf0q0f6tekZ litemall[24220]: Unable to find Java
Jul 20 23:16:59 iZbp1c8cdf0fuf0q0f6tekZ systemd[1]: litemall.service: Control process exited, code=exited status=1
Jul 20 23:16:59 iZbp1c8cdf0fuf0q0f6tekZ systemd[1]: Failed to start LSB: litemall-all.
Jul 20 23:16:59 iZbp1c8cdf0fuf0q0f6tekZ systemd[1]: litemall.service: Unit entered failed state.
Jul 20 23:16:59 iZbp1c8cdf0fuf0q0f6tekZ systemd[1]: litemall.service: Failed with result 'exit-code'.
`

因为自己是做android开发的，对于这种错误 ，没啥知识储备，也百度过，发现处理起来有点吃力。不知道如何解决。

**Comment by hejiafeng** [comment]
装了jdk ,就好了。。
