### ISSUE TITLE
微信登录失败，生成的参数中secret为*****

### ISSUE THREAD

**Issue by qixinynan** [linlinjava/litemall#525]
【请求地址】: https://api.weixin.qq.com/sns/jscode2session?access_token=62_kJQY32CriGeTSey2fyeq0_Vf7XlaY7waNHUdQwNMLAmTHg7TLYH7_IpY5RPRNyGMOTjw8lXCibqCQ_qTdfqNre1q8jCKrFazzdFjmhKTiM49AWcuTXpJL9J5fpIRLQdAIAICH
【请求参数】：js_code=03375n0004t9UO10Es100MqDRb175n0J&secret=******&grant_type=authorization_code&appid=wxa5b486c6b918ecfb
【错误信息】：错误代码：40029, 错误信息：code 无效，微信原始报文：{"errcode":40029,"errmsg":"invalid code, rid: 6371e1f8-7f778b86-752334e5"}
me.chanjar.weixin.common.error.WxErrorException: 错误代码：40029, 错误信息：code 无效，微信原始报文：{"errcode":40029,"errmsg":"invalid code, rid: 6371e1f8-7f778b86-752334e5"}

其中的secret中的******并非我为了保密而修改后的，是自动拼接时即为此结果，但litemall-core中的application-core中的secret已填写

litemall:
  # 开发者应该设置成自己的wx相关信息
  wx:
    app-id: wx380e0bd756XXXXX
    app-secret: 65ff158223105115c0099d615XXXXX
    mch-id: 111111
    mch-key: xxxxxx
    notify-url: http://122.51.199.160:8080/wx/order/pay-notify
    # 商户证书文件路径
    # 请参考“商户证书”一节 https://pay.weixin.qq.com/wiki/doc/api/wxa/wxa_api.php?chapter=4_3
    key-path: xxxxx

**Comment by linlinjava** [comment]
这个你可以在IDEA中全局搜索看看你的秘钥是否修改。
另外也可以在根目录执行mvn clean清除已编译文件。
