### ISSUE TITLE
litemall-admin 运行报错,错误信息

### ISSUE THREAD

**Issue by zhangxuekui** [linlinjava/litemall#527]
ERROR  Failed to compile with 181 errors
These dependencies were not found:

* core-js/modules/es.array-buffer.constructor.js in ./src/vendor/Export2Excel.js
* core-js/modules/es.array-buffer.slice.js in ./src/vendor/Export2Excel.js
* core-js/modules/es.array.concat.js in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/Breadcrumb/index.vue?vue&type=script&lang=js&, ./src/store/modules/permission.js and 3 others
* core-js/modules/es.array.filter.js in ./node_modules/@babel/runtime/helpers/objectSpread2.js, ./src/main.js and 3 others
* core-js/modules/es.array.find-index.js in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/views/layout/components/TagsView/ScrollPane.vue?vue&type=script&lang=js&
* core-js/modules/es.array.from.js in ./node_modules/@babel/runtime/helpers/unsupportedIterableToArray.js, ./src/utils/index.js
* core-js/modules/es.array.includes.js in ./src/directive/permission/permission.js, ./src/store/modules/tagsView.js and 2 others
* core-js/modules/es.array.join.js in ./src/utils/index.js
* core-js/modules/es.array.map.js in ./src/icons/index.js, ./src/utils/index.js and 2 others
* core-js/modules/es.array.push.js in ./node_modules/@babel/runtime/helpers/objectSpread2.js, ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/Breadcrumb/index.vue?vue&type=script&lang=js& and 15 others
* core-js/modules/es.array.slice.js in ./node_modules/@babel/runtime/helpers/regeneratorRuntime.js, ./src/filters/index.js and 4 others
* core-js/modules/es.array.splice.js in ./src/store/modules/tagsView.js, ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/views/goods/edit.vue?vue&type=script&lang=js& and 3 others
* core-js/modules/es.array.unshift.js in ./src/vendor/Export2Excel.js, ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/views/goods/edit.vue?vue&type=script&lang=js& and 3 others
* core-js/modules/es.date.to-primitive.js in ./node_modules/@babel/runtime/helpers/toPrimitive.js
* core-js/modules/es.error.cause.js in ./node_modules/@babel/runtime/helpers/toPrimitive.js, ./src/directive/permission/permission.js and 3 others
* core-js/modules/es.function.name.js in ./node_modules/@babel/runtime/helpers/regeneratorRuntime.js, ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/Breadcrumb/index.vue?vue&type=script&lang=js& and 4 others
* core-js/modules/es.json.to-string-tag.js in ./node_modules/@babel/runtime/helpers/regeneratorRuntime.js
* core-js/modules/es.math.to-string-tag.js in ./node_modules/@babel/runtime/helpers/regeneratorRuntime.js
* core-js/modules/es.number.constructor.js in ./node_modules/@babel/runtime/helpers/toPrimitive.js, ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/BackToTop/index.vue?vue&type=script&lang=js& and 3 others
* core-js/modules/es.number.to-fixed.js in ./src/filters/index.js
* core-js/modules/es.object.get-own-property-descriptor.js in ./node_modules/@babel/runtime/helpers/interopRequireWildcard.js
* core-js/modules/es.object.get-own-property-descriptors.js in ./node_modules/@babel/runtime/helpers/objectSpread2.js
* core-js/modules/es.object.get-prototype-of.js in ./node_modules/@babel/runtime/helpers/regeneratorRuntime.js
* core-js/modules/es.object.keys.js in ./node_modules/@babel/runtime/helpers/objectSpread2.js, ./src/main.js and 1 other
* core-js/modules/es.object.proto.js in ./node_modules/@babel/runtime/helpers/regeneratorRuntime.js
* core-js/modules/es.object.set-prototype-of.js in ./node_modules/@babel/runtime/helpers/regeneratorRuntime.js
* core-js/modules/es.object.to-string.js in ./node_modules/@babel/runtime/helpers/interopRequireWildcard.js, ./src/main.js and 16 others
* core-js/modules/es.regexp.exec.js in ./node_modules/@babel/runtime/helpers/unsupportedIterableToArray.js, ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/SizeSelect/index.vue?vue&type=script&lang=js& and 5 others
* core-js/modules/es.regexp.test.js in ./node_modules/@babel/runtime/helpers/unsupportedIterableToArray.js, ./src/utils/index.js
* core-js/modules/es.regexp.to-string.js in ./src/filters/index.js, ./src/vendor/Export2Excel.js and 1 other
* core-js/modules/es.set.js in ./src/utils/index.js
* core-js/modules/es.string.includes.js in ./src/directive/permission/permission.js, ./src/store/modules/tagsView.js and 2 others
* core-js/modules/es.string.iterator.js in ./node_modules/@babel/runtime/helpers/interopRequireWildcard.js, ./src/utils/index.js
* core-js/modules/es.string.match.js in ./src/utils/index.js
* core-js/modules/es.string.replace.js in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/SizeSelect/index.vue?vue&type=script&lang=js&, ./src/filters/index.js and 3 others
* core-js/modules/es.string.search.js in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/views/login/authredirect.vue?vue&type=script&lang=js&
* core-js/modules/es.string.starts-with.js in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/Breadcrumb/index.vue?vue&type=script&lang=js&
* core-js/modules/es.string.trim.js in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/Breadcrumb/index.vue?vue&type=script&lang=js&, ./src/store/modules/user.js and 1 other
* core-js/modules/es.symbol.async-iterator.js in ./node_modules/@babel/runtime/helpers/regeneratorRuntime.js
* core-js/modules/es.symbol.description.js in ./node_modules/@babel/runtime/helpers/toPrimitive.js
* core-js/modules/es.symbol.iterator.js in ./node_modules/@babel/runtime/helpers/typeof.js
* core-js/modules/es.symbol.js in ./node_modules/@babel/runtime/helpers/typeof.js
* core-js/modules/es.symbol.to-primitive.js in ./node_modules/@babel/runtime/helpers/toPrimitive.js
* core-js/modules/es.symbol.to-string-tag.js in ./node_modules/@babel/runtime/helpers/regeneratorRuntime.js
* core-js/modules/es.typed-array.at.js in ./src/vendor/Export2Excel.js
* core-js/modules/es.typed-array.copy-within.js in ./src/vendor/Export2Excel.js
* core-js/modules/es.typed-array.every.js in ./src/vendor/Export2Excel.js
* core-js/modules/es.typed-array.fill.js in ./src/vendor/Export2Excel.js
* core-js/modules/es.typed-array.filter.js in ./src/vendor/Export2Excel.js
* core-js/modules/es.typed-array.find-index.js in ./src/vendor/Export2Excel.js
* core-js/modules/es.typed-array.find-last-index.js in ./src/vendor/Export2Excel.js
* core-js/modules/es.typed-array.find-last.js in ./src/vendor/Export2Excel.js
* core-js/modules/es.typed-array.find.js in ./src/vendor/Export2Excel.js
* core-js/modules/es.typed-array.for-each.js in ./src/vendor/Export2Excel.js
* core-js/modules/es.typed-array.includes.js in ./src/vendor/Export2Excel.js
* core-js/modules/es.typed-array.index-of.js in ./src/vendor/Export2Excel.js
* core-js/modules/es.typed-array.iterator.js in ./src/vendor/Export2Excel.js
* core-js/modules/es.typed-array.join.js in ./src/vendor/Export2Excel.js
* core-js/modules/es.typed-array.last-index-of.js in ./src/vendor/Export2Excel.js
* core-js/modules/es.typed-array.map.js in ./src/vendor/Export2Excel.js
* core-js/modules/es.typed-array.reduce-right.js in ./src/vendor/Export2Excel.js
* core-js/modules/es.typed-array.reduce.js in ./src/vendor/Export2Excel.js
* core-js/modules/es.typed-array.reverse.js in ./src/vendor/Export2Excel.js
* core-js/modules/es.typed-array.set.js in ./src/vendor/Export2Excel.js
* core-js/modules/es.typed-array.slice.js in ./src/vendor/Export2Excel.js
* core-js/modules/es.typed-array.some.js in ./src/vendor/Export2Excel.js
* core-js/modules/es.typed-array.sort.js in ./src/vendor/Export2Excel.js
* core-js/modules/es.typed-array.subarray.js in ./src/vendor/Export2Excel.js
* core-js/modules/es.typed-array.to-locale-string.js in ./src/vendor/Export2Excel.js
* core-js/modules/es.typed-array.to-string.js in ./src/vendor/Export2Excel.js
* core-js/modules/es.typed-array.uint8-array.js in ./src/vendor/Export2Excel.js
* core-js/modules/es.weak-map.js in ./node_modules/@babel/runtime/helpers/interopRequireWildcard.js
* core-js/modules/web.dom-collections.for-each.js in ./node_modules/@babel/runtime/helpers/objectSpread2.js, ./src/main.js and 8 others
* core-js/modules/web.dom-collections.iterator.js in ./node_modules/@babel/runtime/helpers/interopRequireWildcard.js, ./src/icons/index.js and 2 others

To install them, you can run: npm install --save core-js/modules/es.array-buffer.constructor.js core-js/modules/es.array-buffer.slice.js core-js/modules/es.array.concat.js core-js/modules/es.array.filter.js core-js/modules/es.array.find-index.js core-js/modules/es.array.from.js core-js/modules/es.array.includes.js core-js/modules/es.array.join.js core-js/modules/es.array.map.js core-js/modules/es.array.push.js core-js/modules/es.array.slice.js core-js/modules/es.array.splice.js core-js/modules/es.array.unshift.js core-js/modules/es.date.to-primitive.js core-js/modules/es.error.cause.js core-js/modules/es.function.name.js core-js/modules/es.json.to-string-tag.js core-js/modules/es.math.to-string-tag.js core-js/modules/es.number.constructor.js core-js/modules/es.number.to-fixed.js core-js/modules/es.object.get-own-property-descriptor.js core-js/modules/es.object.get-own-property-descriptors.js core-js/modules/es.object.get-prototype-of.js core-js/modules/es.object.keys.js core-js/modules/es.object.proto.js core-js/modules/es.object.set-prototype-of.js core-js/modules/es.object.to-string.js core-js/modules/es.regexp.exec.js core-js/modules/es.regexp.test.js core-js/modules/es.regexp.to-string.js core-js/modules/es.set.js core-js/modules/es.string.includes.js core-js/modules/es.string.iterator.js core-js/modules/es.string.match.js core-js/modules/es.string.replace.js core-js/modules/es.string.search.js core-js/modules/es.string.starts-with.js core-js/modules/es.string.trim.js core-js/modules/es.symbol.async-iterator.js core-js/modules/es.symbol.description.js core-js/modules/es.symbol.iterator.js core-js/modules/es.symbol.js core-js/modules/es.symbol.to-primitive.js core-js/modules/es.symbol.to-string-tag.js core-js/modules/es.typed-array.at.js core-js/modules/es.typed-array.copy-within.js core-js/modules/es.typed-array.every.js core-js/modules/es.typed-array.fill.js core-js/modules/es.typed-array.filter.js core-js/modules/es.typed-array.find-index.js core-js/modules/es.typed-array.find-last-index.js core-js/modules/es.typed-array.find-last.js core-js/modules/es.typed-array.find.js core-js/modules/es.typed-array.for-each.js core-js/modules/es.typed-array.includes.js core-js/modules/es.typed-array.index-of.js core-js/modules/es.typed-array.iterator.js core-js/modules/es.typed-array.join.js core-js/modules/es.typed-array.last-index-of.js core-js/modules/es.typed-array.map.js core-js/modules/es.typed-array.reduce-right.js core-js/modules/es.typed-array.reduce.js core-js/modules/es.typed-array.reverse.js core-js/modules/es.typed-array.set.js core-js/modules/es.typed-array.slice.js core-js/modules/es.typed-array.some.js core-js/modules/es.typed-array.sort.js core-js/modules/es.typed-array.subarray.js core-js/modules/es.typed-array.to-locale-string.js core-js/modules/es.typed-array.to-string.js core-js/modules/es.typed-array.uint8-array.js core-js/modules/es.weak-map.js core-js/modules/web.dom-collections.for-each.js core-js/modules/web.dom-collections.iterator.js
Error from chokidar (C:\): Error: EBUSY: resource busy or locked, lstat 'C:\DumpStack.log.tmp'

**Comment by towardsvast** [comment]
大佬解决了吗，我也碰到相同问题了

**Comment by zhangxuekui** [comment]
> 

可能是版本问题,我把涉及到的excel代码删除了就可以启动了,我主要是想看下demo的,还没有用.

**Comment by towardsvast** [comment]
> 

我发现应该也是版本问题，admin模块涉及到的excel代码全部要删除吗

**Comment by Vhibli** [comment]
我升级了两个库
    "file-saver": "^2.0.5",
    "xlsx": "^0.18.5",
然后重新安装core-js
就可以运行了
@towardsvast
