### ISSUE TITLE
基于shiro实现后台安全

### ISSUE THREAD

**Issue by linlinjava** [linlinjava/litemall#54]

**Comment by liuyatao** [comment]
既然使用spring boot为什么不用spring security作为安全框架

**Comment by linlinjava** [comment]
spring security也可以，不过好像有人说比较复杂。

**Comment by tianyu4552** [comment]
shiro简单实用

**Comment by linlinjava** [comment]
权限管理已经完成。
管理后台的后端基于shiro实现权限校验；管理后台的前端则实现菜单权限和按钮权限。
后面可能会微调。
