### ISSUE TITLE
数据库文件

### ISSUE THREAD

**Issue by xiaoLogin** [linlinjava/litemall#55]
数据库文件没有同步更新，缺少表

**Comment by linlinjava** [comment]
具体报错信息，以及哪个表

**Comment by xiaoLogin** [comment]
我看到order表的sql里，没有groupon_price字段；
同时，groupon的相关表也是没有的

**Comment by linlinjava** [comment]
请不要下载dev分支，而应该是master分支，目前master分支还没有支持groupon相关业务。
