### ISSUE TITLE
master分支小程序登录报40125

### ISSUE THREAD

**Issue by gitkmw** [linlinjava/litemall#551]
描述：1. 已修改litemall-wx/project.config.json里的appid为自己的。2. 已修改application-core.yml里的app-id和app-secret为自己的。

报错信息：me.chanjar.weixin.common.error.WxErrorException: 错误代码：40125, 错误信息：invalid appsecret rid: xxx。

**Comment by UACurry** [comment]
你好，请问解决了嘛
