### ISSUE TITLE
后台禁用广告之后，小程序端无反应

### ISSUE THREAD

**Issue by everythinggood** [linlinjava/litemall#61]
请修改db端AdService代码：
public List<LitemallAd> queryIndex() {
        LitemallAdExample example = new LitemallAdExample();
        example.or().andPositionEqualTo((byte)1).andDeletedEqualTo(false).andEnabledEqualTo(true);
        return adMapper.selectByExample(example);
    }

**Comment by menethil** [comment]
感谢提交，已修复
