### ISSUE TITLE
使用默认账号登陆后立刻提示未登陆

### ISSUE THREAD

**Issue by netssfy** [linlinjava/litemall#64]
根据DOC部署后，打开管理后台用默认账号admin123登陆
看到dashboard后立马看到未登录提示窗口，点击确定后返回登陆页面
但是我在CONSOLE里看到login返回的JSON是登陆成功

![image](https://user-images.githubusercontent.com/6095138/44160684-b9d16000-a0ed-11e8-9a58-38c900bb9ec7.png)

**Comment by linlinjava** [comment]
你好，请问是最新的代码吗。之前代码有这个问题，之后已经修复。

**Comment by netssfy** [comment]
几天前的版本，我重新PULL一下，谢谢
