### ISSUE TITLE
任意文件下载漏洞

### ISSUE THREAD

**Issue by 360CodeSafe** [linlinjava/litemall#76]
您好:
360代码卫士团队在litemall项目中发现了一个任意文件下载的漏洞，还请确认，详细信息如下：
在WxStorageController.java文件中提供了文件下载的功能
![default](https://user-images.githubusercontent.com/39950310/46854796-90eef200-ce34-11e8-8097-8cc0c8970185.png)
但由于没有对文件名做校验，导致恶意攻击者可以下载任意类型的文件，并且可以通过../来回溯下载任意路径下的文件。

**Comment by linlinjava** [comment]
非常感谢对安全的帮助，这里我增加了对../字符串的校验49ab94d0052672d4fb642505d44b94a18abea332。
不过，我放宽了对文件名的校验，目前我觉得对任意类型文件下载不要紧。
