### ISSUE TITLE
關於設計模式

### ISSUE THREAD

**Issue by Tong-c** [linlinjava/litemall#77]
請問，在這樣一個完整個的電商項目里，有運用到哪些設計模式呢？一直在學習設計模式，但還是無法自如運用，想結合具體業務瞭解下，謝謝。

**Comment by linlinjava** [comment]
你好，虽然我也想灵活使用设计模式，但是实际开发时没有考虑任何设计模式，只是需要什么功能然后开发。所以，这里可能帮不上。
