### ISSUE TITLE
添加收货地址失败

### ISSUE THREAD

**Issue by mryu-org** [linlinjava/litemall#78]
正常购买流程，在添加地址环节填写收货地址后点击“保存”按钮后无法保存，卡在这里无法进行下一步。
<img width="1308" alt="2018-10-23 2 50 08" src="https://user-images.githubusercontent.com/9658267/47341212-0ed3b880-d6d3-11e8-8f7a-669112d5eed2.png">

**Comment by moqijiasudu** [comment]
if(addressService.findById(pid) == null){
//            return ResponseUtil.badArgumentValue();
//        }

我刚刚clone的 也是这个问题。把这段代码注释或者改掉就好了。

**Comment by mryu-org** [comment]
> if(addressService.findById(pid) == null){
> // return ResponseUtil.badArgumentValue();
> // }
> 
> 我刚刚clone的 也是这个问题。把这段代码注释或者改掉就好了。

具体文件路径是？

**Comment by mryu-org** [comment]
> if(addressService.findById(pid) == null){
> // return ResponseUtil.badArgumentValue();
> // }
> 
> 我刚刚clone的 也是这个问题。把这段代码注释或者改掉就好了。

我把你注释的这段注释后还是不行，保存不了。另外拉取新的代码，点击商品详情时图片也不显示了。

**Comment by linlinjava** [comment]
看到了，我校验代码写错了，现在已修复cd27350a224b610552f0f21d8d32dd51f96b75cb

其他问题麻烦单独开issue吧，我会优先处理反馈issue中的问题。
