### ISSUE TITLE
mvn install卡顿

### ISSUE THREAD

**Issue by mryu-org** [linlinjava/litemall#81]
执行mvn install 时卡顿，可以考虑去掉。
https://repo.maven.apache.org/maven2/com/qiniu/qiniu-java-sdk/maven-metadata.xml
<img width="697" alt="2018-10-26 11 21 08" src="https://user-images.githubusercontent.com/9658267/47542749-79723780-d911-11e8-8472-8abb4484ceb3.png">

**Comment by linlinjava** [comment]
目前我没有遇到这个问题，所以不会考虑去掉。
谢谢你的建议。
