### ISSUE TITLE
登录连接超时（后台不能连接，请联系系统管理员）

### ISSUE THREAD

**Issue by riddlerx** [linlinjava/litemall#87]
部署之后，登录后台管理界面提示“登录连接超时（后台不能连接，请联系系统管理员）”

**Comment by riddlerx** [comment]
版本是今天最新的

**Comment by linlinjava** [comment]
https://linlinjava.gitbook.io/litemall/faq#22-deng-lu-lian-jie-chao-shi-lian-xi-guan-li-yuan

**Comment by linlinjava** [comment]
请仔细按照[1.4开发方案](https://linlinjava.gitbook.io/litemall/project#14-kai-fa-fang-an)文档再试一下，应该可以的。
