### ISSUE TITLE
litemall-admin

### ISSUE THREAD

**Issue by liuhe00** [linlinjava/litemall#88]

**Comment by liuhe00** [comment]
请问后台打成war包放到远程tomcat上可以运行，litemall-admin执行build后，放到war包解压后的目录里，运行总是报这个错。为什么总是从我本地硬盘中，查找相关的文件？
![Uploading image.png…]()
请问有一套前后台打包放到远程服务器上运行的实践吗？

**Comment by linlinjava** [comment]
1. 目前不支持war，仅支持打包二进制jar包。
2. 文档里面已经写了我的部署阶段、上线阶段的理解，你可以看一下，如果哪里不完善或者可以补充的，欢迎讨论。
