### ISSUE TITLE
后台更新商品价格报错

### ISSUE THREAD

**Issue by mryu-org** [linlinjava/litemall#90]
1.导入工程sql数据后更改商品价格提示错误如下：
![2018-11-21 10 57 23](https://user-images.githubusercontent.com/9658267/48816280-8fdaaa00-ed7c-11e8-95cb-c362b34b6ca7.png)

**Comment by linlinjava** [comment]
我测试了价格可以修改，你可以自己DEBUG后台看看，在哪里报错以及具体哪个参数验证失败。
