### ISSUE TITLE
支付按钮多次点击会生成多个订单

### ISSUE THREAD

**Issue by WinterChenS** [linlinjava/litemall#91]
重复点击支付按钮会生成多个订单

**Comment by linlinjava** [comment]
你好，能不能再具体一些，例如如何产生，以及订单怎么变成多个了。
之前的测试中，支付以后只会生产订单一个。

**Comment by WinterChenS** [comment]
@linlinjava 我是在demo中看到这个问题，代码运行是没有问题的

**Comment by linlinjava** [comment]
好的，谢谢反馈。那我关闭了。
