### ISSUE TITLE
English translation

### ISSUE THREAD

**Issue by pettomartino** [linlinjava/litemall#92]
It looks a really interesting project. I'd appreciate a English translation of this.

**Comment by linlinjava** [comment]
Thanks for your advice.

Let me introduce this project a little here.
This is yet a lite mall system as it is named "litemall", which contains two parts.
The first part is mall management platform, which is implemented by spring boot (back end) and vue (front end). Admin can use this platform to add goods and other work.
The second part is wechat user platform, which is implemented by spring boot (back end) and miniprogram (front end). The mall users can use the wechat app and search the litemall plugin for shopping.

However, I think it may be useless to translate into English. Miniprogram language is dedicated web language developed by tencent company, and can only be used in its wechat app. You can learn more from this site https://developers.weixin.qq.com/miniprogram/en/dev/index.html.

**Comment by pettomartino** [comment]
Yes, seems like the project as whole doesn't make much sense in English indeed, however the combination of technologies and how they integrate with each other looks interesting and can inspire people to use same technologies(myself included)
Anyway, I understand your point, congrats for the project.

**Comment by linlinjava** [comment]
Actually I have a plan to implement user mobile web app in the future release, based on vue stack. Then packet this web app into Android or iOS platform using apache cordova or other technology. I think it shall be a very interesting experiment. At that time, it will be the right time to translate into English.

Anyway I suggest you may try this vue admin https://github.com/PanJiaChen/vue-element-admin. The litemall admin platform is based on this project.
