### ISSUE TITLE
sql错误

### ISSUE THREAD

**Issue by yutungnet** [linlinjava/litemall#94]
删除用户sql，不能是用 if exist 判断，直接删除就可以了。

**Comment by yutungnet** [comment]
直接drop user，加上  if exist 判断 我这里报错了

**Comment by linlinjava** [comment]
目前只有你遇到这个问题，所以我这里可能暂时不会这么做吧。

**Comment by ohmydengzi** [comment]
mysql 版本5.7 及以上才支持 drop user if exists

**Comment by linlinjava** [comment]
感谢反馈，在FAQ文档中写了相关注意内容
