### ISSUE TITLE
小程序端获取不到运单号

### ISSUE THREAD

**Issue by mryu-org** [linlinjava/litemall#97]
后台已发货，填写了快递名称：韵达快递和单号，小程序端不显示。
<img width="696" alt="2018-12-01 10 01 35" src="https://user-images.githubusercontent.com/9658267/49322982-42b2c100-f550-11e8-880c-750409f88d6e.png">

**Comment by linlinjava** [comment]
1. 快递你没有申请账号并配置
2. 你自己可以DEBUG一下，后台那里有没有返回数据或者报错。

**Comment by xiaojia21190** [comment]
快递申请的话，沙箱测试的appkey不可以是吗？
