### ISSUE TITLE
小程序首页推荐修改

### ISSUE THREAD

**Issue by mryu-org** [linlinjava/litemall#99]
hi，居家、餐厨这两个分类到哪里替换成其它分类？数据里？
<img width="269" alt="2018-12-01 11 12 54" src="https://user-images.githubusercontent.com/9658267/49323701-4d725380-f55a-11e8-8db8-76af3132f22c.png">

**Comment by linlinjava** [comment]
这个不是BUG，是你自己应该看看数据是如何产生的。
我觉得你应该有能力找到分类产生的地方然后根据自己需求修改。

**Comment by mryu-org** [comment]
商品类目-》父类目ID为0即可在首页显示，不过首页默认显示3个类目。

**Comment by mryu-org** [comment]
见WxHomeController类
